name: Compile ChiyoTatsu
on:
    push:
        branches:
            - main

jobs:
    statically-compile-chiyotatsu:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1
                  fetch-tags: true
                  submodules: recursive

            - name: Install compilers
              run: |
                  sudo apt install -y build-essential

            - name: Generate Version Number
              run: |
                  CURRENT_VER="$(./increment_version.sh)"
                  echo "CURRENT_VER=$CURRENT_VER" >> $GITHUB_ENV

            - name: Compile Libs
              run: echo hello

            - name: Compile Chiyotatsu
              run: |
                  make clean
                  make -j4 elf_release_32
                  mv chiyotatsu.elf chiyotatsu-x86_32-${{ env.CURRENT_VER }}.elf
                  make clean
                  make -j4 elf_release_64
                  mv chiyotatsu.elf chiyotatsu-x86_64-${{ env.CURRENT_VER }}.elf
                  make clean
                  make -j4 exe_release_32
                  mv chiyotatsu.exe chiyotatsu-x86_64-${{ env.CURRENT_VER }}.exe
                  make clean
                  make -j4 exe_release_64
                  mv chiyotatsu.exe chiyotatsu-x86_64-${{ env.CURRENT_VER }}.exe

            - name: Create Release and Upload Assets
              uses: softprops/action-gh-release@v2
              with:
                  name: 'Release ${{ env.CURRENT_VER }}'
                  body: ${{ github.event.head_commit.message }}
                  tag_name: ${{ env.CURRENT_VER }}
                  files: |
                      chiyotatsu-x86_32-${{ env.CURRENT_VER }}.elf
                      chiyotatsu-x86_64-${{ env.CURRENT_VER }}.elf
                      chiyotatsu-x86_32-${{ env.CURRENT_VER }}.exe
                      chiyotatsu-x86_64-${{ env.CURRENT_VER }}.exe
                  draft: false
                  prerelease: false
