// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: backup_preference.proto

package backup_preference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// For readability?
type PreferenceValue int32

const (
	PreferenceValue_UNKNOWN          PreferenceValue = 0
	PreferenceValue_INT_VALUE        PreferenceValue = 2
	PreferenceValue_LONG_VALUE       PreferenceValue = 3
	PreferenceValue_FLOAT_VALUE      PreferenceValue = 4
	PreferenceValue_STRING_VALUE     PreferenceValue = 5
	PreferenceValue_BOOL_VALUE       PreferenceValue = 6
	PreferenceValue_STRING_SET_VALUE PreferenceValue = 7
)

// Enum value maps for PreferenceValue.
var (
	PreferenceValue_name = map[int32]string{
		0: "UNKNOWN",
		2: "INT_VALUE",
		3: "LONG_VALUE",
		4: "FLOAT_VALUE",
		5: "STRING_VALUE",
		6: "BOOL_VALUE",
		7: "STRING_SET_VALUE",
	}
	PreferenceValue_value = map[string]int32{
		"UNKNOWN":          0,
		"INT_VALUE":        2,
		"LONG_VALUE":       3,
		"FLOAT_VALUE":      4,
		"STRING_VALUE":     5,
		"BOOL_VALUE":       6,
		"STRING_SET_VALUE": 7,
	}
)

func (x PreferenceValue) Enum() *PreferenceValue {
	p := new(PreferenceValue)
	*p = x
	return p
}

func (x PreferenceValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreferenceValue) Descriptor() protoreflect.EnumDescriptor {
	return file_backup_preference_proto_enumTypes[0].Descriptor()
}

func (PreferenceValue) Type() protoreflect.EnumType {
	return &file_backup_preference_proto_enumTypes[0]
}

func (x PreferenceValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreferenceValue.Descriptor instead.
func (PreferenceValue) EnumDescriptor() ([]byte, []int) {
	return file_backup_preference_proto_rawDescGZIP(), []int{0}
}

type BackupPreference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are assignable to Value:
	//
	//	*BackupPreference_IntValue
	//	*BackupPreference_LongValue
	//	*BackupPreference_FloatValue
	//	*BackupPreference_StringValue
	//	*BackupPreference_BoolValue
	//	*BackupPreference_StringSetValue
	Value isBackupPreference_Value `protobuf_oneof:"value"`
}

func (x *BackupPreference) Reset() {
	*x = BackupPreference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backup_preference_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupPreference) ProtoMessage() {}

func (x *BackupPreference) ProtoReflect() protoreflect.Message {
	mi := &file_backup_preference_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupPreference.ProtoReflect.Descriptor instead.
func (*BackupPreference) Descriptor() ([]byte, []int) {
	return file_backup_preference_proto_rawDescGZIP(), []int{0}
}

func (x *BackupPreference) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (m *BackupPreference) GetValue() isBackupPreference_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *BackupPreference) GetIntValue() int32 {
	if x, ok := x.GetValue().(*BackupPreference_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (x *BackupPreference) GetLongValue() int64 {
	if x, ok := x.GetValue().(*BackupPreference_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (x *BackupPreference) GetFloatValue() float32 {
	if x, ok := x.GetValue().(*BackupPreference_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (x *BackupPreference) GetStringValue() string {
	if x, ok := x.GetValue().(*BackupPreference_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *BackupPreference) GetBoolValue() bool {
	if x, ok := x.GetValue().(*BackupPreference_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *BackupPreference) GetStringSetValue() *StringSet {
	if x, ok := x.GetValue().(*BackupPreference_StringSetValue); ok {
		return x.StringSetValue
	}
	return nil
}

type isBackupPreference_Value interface {
	isBackupPreference_Value()
}

type BackupPreference_IntValue struct {
	IntValue int32 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type BackupPreference_LongValue struct {
	LongValue int64 `protobuf:"varint,3,opt,name=long_value,json=longValue,proto3,oneof"`
}

type BackupPreference_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type BackupPreference_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type BackupPreference_BoolValue struct {
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type BackupPreference_StringSetValue struct {
	StringSetValue *StringSet `protobuf:"bytes,7,opt,name=string_set_value,json=stringSetValue,proto3,oneof"`
}

func (*BackupPreference_IntValue) isBackupPreference_Value() {}

func (*BackupPreference_LongValue) isBackupPreference_Value() {}

func (*BackupPreference_FloatValue) isBackupPreference_Value() {}

func (*BackupPreference_StringValue) isBackupPreference_Value() {}

func (*BackupPreference_BoolValue) isBackupPreference_Value() {}

func (*BackupPreference_StringSetValue) isBackupPreference_Value() {}

type BackupSourcePreferences struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceKey string              `protobuf:"bytes,1,opt,name=source_key,json=sourceKey,proto3" json:"source_key,omitempty"`
	Prefs     []*BackupPreference `protobuf:"bytes,2,rep,name=prefs,proto3" json:"prefs,omitempty"`
}

func (x *BackupSourcePreferences) Reset() {
	*x = BackupSourcePreferences{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backup_preference_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupSourcePreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSourcePreferences) ProtoMessage() {}

func (x *BackupSourcePreferences) ProtoReflect() protoreflect.Message {
	mi := &file_backup_preference_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSourcePreferences.ProtoReflect.Descriptor instead.
func (*BackupSourcePreferences) Descriptor() ([]byte, []int) {
	return file_backup_preference_proto_rawDescGZIP(), []int{1}
}

func (x *BackupSourcePreferences) GetSourceKey() string {
	if x != nil {
		return x.SourceKey
	}
	return ""
}

func (x *BackupSourcePreferences) GetPrefs() []*BackupPreference {
	if x != nil {
		return x.Prefs
	}
	return nil
}

type StringSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StringSet []string `protobuf:"bytes,1,rep,name=string_set,json=stringSet,proto3" json:"string_set,omitempty"`
}

func (x *StringSet) Reset() {
	*x = StringSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backup_preference_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringSet) ProtoMessage() {}

func (x *StringSet) ProtoReflect() protoreflect.Message {
	mi := &file_backup_preference_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringSet.ProtoReflect.Descriptor instead.
func (*StringSet) Descriptor() ([]byte, []int) {
	return file_backup_preference_proto_rawDescGZIP(), []int{2}
}

func (x *StringSet) GetStringSet() []string {
	if x != nil {
		return x.StringSet
	}
	return nil
}

var File_backup_preference_proto protoreflect.FileDescriptor

var file_backup_preference_proto_rawDesc = []byte{
	0x0a, 0x17, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x74, 0x61, 0x63, 0x68, 0x69,
	0x79, 0x6f, 0x6d, 0x69, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22,
	0xa4, 0x02, 0x0a, 0x10, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0a, 0x66,
	0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f,
	0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x4c, 0x0a, 0x10, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74, 0x61, 0x63, 0x68,
	0x69, 0x79, 0x6f, 0x6d, 0x69, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x2e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x76, 0x0a, 0x17, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4b, 0x65, 0x79,
	0x12, 0x3c, 0x0a, 0x05, 0x70, 0x72, 0x65, 0x66, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x74, 0x61, 0x63, 0x68, 0x69, 0x79, 0x6f, 0x6d, 0x69, 0x5f, 0x70, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x05, 0x70, 0x72, 0x65, 0x66, 0x73, 0x22, 0x2b,
	0x0a, 0x0a, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x74, 0x2a, 0x86, 0x01, 0x0a, 0x0f,
	0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x49, 0x4e, 0x54, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4c,
	0x4f, 0x4e, 0x47, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x46,
	0x4c, 0x4f, 0x41, 0x54, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c,
	0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x05, 0x12, 0x0e,
	0x0a, 0x0a, 0x42, 0x4f, 0x4f, 0x4c, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x06, 0x12, 0x14,
	0x0a, 0x10, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x56, 0x41, 0x4c,
	0x55, 0x45, 0x10, 0x07, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x6f, 0x69, 0x73, 0x65, 0x6e, 0x2f, 0x63, 0x68, 0x69, 0x79, 0x6f,
	0x2d, 0x74, 0x61, 0x74, 0x73, 0x75, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x5f, 0x67, 0x6f, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x70, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backup_preference_proto_rawDescOnce sync.Once
	file_backup_preference_proto_rawDescData = file_backup_preference_proto_rawDesc
)

func file_backup_preference_proto_rawDescGZIP() []byte {
	file_backup_preference_proto_rawDescOnce.Do(func() {
		file_backup_preference_proto_rawDescData = protoimpl.X.CompressGZIP(file_backup_preference_proto_rawDescData)
	})
	return file_backup_preference_proto_rawDescData
}

var file_backup_preference_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_backup_preference_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_backup_preference_proto_goTypes = []interface{}{
	(PreferenceValue)(0),            // 0: tachiyomi_preference.PreferenceValue
	(*BackupPreference)(nil),        // 1: tachiyomi_preference.BackupPreference
	(*BackupSourcePreferences)(nil), // 2: tachiyomi_preference.BackupSourcePreferences
	(*StringSet)(nil),               // 3: tachiyomi_preference.string_set
}
var file_backup_preference_proto_depIdxs = []int32{
	3, // 0: tachiyomi_preference.BackupPreference.string_set_value:type_name -> tachiyomi_preference.string_set
	1, // 1: tachiyomi_preference.BackupSourcePreferences.prefs:type_name -> tachiyomi_preference.BackupPreference
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_backup_preference_proto_init() }
func file_backup_preference_proto_init() {
	if File_backup_preference_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backup_preference_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupPreference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backup_preference_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupSourcePreferences); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backup_preference_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_backup_preference_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*BackupPreference_IntValue)(nil),
		(*BackupPreference_LongValue)(nil),
		(*BackupPreference_FloatValue)(nil),
		(*BackupPreference_StringValue)(nil),
		(*BackupPreference_BoolValue)(nil),
		(*BackupPreference_StringSetValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backup_preference_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backup_preference_proto_goTypes,
		DependencyIndexes: file_backup_preference_proto_depIdxs,
		EnumInfos:         file_backup_preference_proto_enumTypes,
		MessageInfos:      file_backup_preference_proto_msgTypes,
	}.Build()
	File_backup_preference_proto = out.File
	file_backup_preference_proto_rawDesc = nil
	file_backup_preference_proto_goTypes = nil
	file_backup_preference_proto_depIdxs = nil
}
