/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backup_source.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backup_source.pb-c.h"
void   broken_backup_source__init
                     (BrokenBackupSource         *message)
{
  static const BrokenBackupSource init_value = BROKEN_BACKUP_SOURCE__INIT;
  *message = init_value;
}
size_t broken_backup_source__get_packed_size
                     (const BrokenBackupSource *message)
{
  assert(message->base.descriptor == &broken_backup_source__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t broken_backup_source__pack
                     (const BrokenBackupSource *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &broken_backup_source__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t broken_backup_source__pack_to_buffer
                     (const BrokenBackupSource *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &broken_backup_source__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BrokenBackupSource *
       broken_backup_source__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BrokenBackupSource *)
     protobuf_c_message_unpack (&broken_backup_source__descriptor,
                                allocator, len, data);
}
void   broken_backup_source__free_unpacked
                     (BrokenBackupSource *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &broken_backup_source__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   backup_source__init
                     (BackupSource         *message)
{
  static const BackupSource init_value = BACKUP_SOURCE__INIT;
  *message = init_value;
}
size_t backup_source__get_packed_size
                     (const BackupSource *message)
{
  assert(message->base.descriptor == &backup_source__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t backup_source__pack
                     (const BackupSource *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &backup_source__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t backup_source__pack_to_buffer
                     (const BackupSource *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &backup_source__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BackupSource *
       backup_source__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BackupSource *)
     protobuf_c_message_unpack (&backup_source__descriptor,
                                allocator, len, data);
}
void   backup_source__free_unpacked
                     (BackupSource *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &backup_source__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor broken_backup_source__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BrokenBackupSource, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sourceId",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(BrokenBackupSource, sourceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned broken_backup_source__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = sourceId */
};
static const ProtobufCIntRange broken_backup_source__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor broken_backup_source__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BrokenBackupSource",
  "BrokenBackupSource",
  "BrokenBackupSource",
  "",
  sizeof(BrokenBackupSource),
  2,
  broken_backup_source__field_descriptors,
  broken_backup_source__field_indices_by_name,
  1,  broken_backup_source__number_ranges,
  (ProtobufCMessageInit) broken_backup_source__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor backup_source__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BackupSource, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sourceId",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(BackupSource, sourceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned backup_source__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = sourceId */
};
static const ProtobufCIntRange backup_source__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor backup_source__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BackupSource",
  "BackupSource",
  "BackupSource",
  "",
  sizeof(BackupSource),
  2,
  backup_source__field_descriptors,
  backup_source__field_indices_by_name,
  1,  backup_source__number_ranges,
  (ProtobufCMessageInit) backup_source__init,
  NULL,NULL,NULL    /* reserved[123] */
};
