/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backup_tracking.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backup_tracking.pb-c.h"
void   backup_tracking__init
                     (BackupTracking         *message)
{
  static const BackupTracking init_value = BACKUP_TRACKING__INIT;
  *message = init_value;
}
size_t backup_tracking__get_packed_size
                     (const BackupTracking *message)
{
  assert(message->base.descriptor == &backup_tracking__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t backup_tracking__pack
                     (const BackupTracking *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &backup_tracking__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t backup_tracking__pack_to_buffer
                     (const BackupTracking *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &backup_tracking__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BackupTracking *
       backup_tracking__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BackupTracking *)
     protobuf_c_message_unpack (&backup_tracking__descriptor,
                                allocator, len, data);
}
void   backup_tracking__free_unpacked
                     (BackupTracking *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &backup_tracking__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor backup_tracking__field_descriptors[12] =
{
  {
    "syncId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BackupTracking, syncid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "libraryId",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(BackupTracking, libraryid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mediaIdInt",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BackupTracking, mediaidint),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trackingUrl",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BackupTracking, trackingurl),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "title",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BackupTracking, title),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lastChapterRead",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BackupTracking, lastchapterread),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "totalChapters",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BackupTracking, totalchapters),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BackupTracking, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BackupTracking, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "startedReadingDate",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(BackupTracking, startedreadingdate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "finishedReadingDate",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(BackupTracking, finishedreadingdate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mediaId",
    100,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(BackupTracking, mediaid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned backup_tracking__field_indices_by_name[] = {
  10,   /* field[10] = finishedReadingDate */
  5,   /* field[5] = lastChapterRead */
  1,   /* field[1] = libraryId */
  11,   /* field[11] = mediaId */
  2,   /* field[2] = mediaIdInt */
  7,   /* field[7] = score */
  9,   /* field[9] = startedReadingDate */
  8,   /* field[8] = status */
  0,   /* field[0] = syncId */
  4,   /* field[4] = title */
  6,   /* field[6] = totalChapters */
  3,   /* field[3] = trackingUrl */
};
static const ProtobufCIntRange backup_tracking__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 100, 11 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor backup_tracking__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BackupTracking",
  "BackupTracking",
  "BackupTracking",
  "",
  sizeof(BackupTracking),
  12,
  backup_tracking__field_descriptors,
  backup_tracking__field_indices_by_name,
  2,  backup_tracking__number_ranges,
  (ProtobufCMessageInit) backup_tracking__init,
  NULL,NULL,NULL    /* reserved[123] */
};
