/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backup_manga.proto */

#ifndef PROTOBUF_C_backup_5fmanga_2eproto__INCLUDED
#define PROTOBUF_C_backup_5fmanga_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "backup_chapter.pb-c.h"
#include "backup_history.pb-c.h"
#include "backup_tracking.pb-c.h"
#include "manga_update_strategy.pb-c.h"

typedef struct BackupManga BackupManga;


/* --- enums --- */


/* --- messages --- */

struct  BackupManga
{
  ProtobufCMessage base;
  int64_t source;
  char *url;
  char *title;
  char *artist;
  char *author;
  char *description;
  size_t n_genre;
  char **genre;
  int32_t status;
  char *thumbnailurl;
  char *customcover;
  int64_t lastupdate;
  int64_t lastinit;
  int64_t dateadded;
  int32_t viewer;
  int32_t flags;
  size_t n_chapters;
  BackupChapter **chapters;
  size_t n_categories;
  int64_t *categories;
  size_t n_tracking;
  BackupTracking **tracking;
  protobuf_c_boolean favorite;
  int32_t chapterflags;
  size_t n_brokenhistory;
  BrokenBackupHistory **brokenhistory;
  int32_t viewer_flags;
  size_t n_history;
  BackupHistory **history;
  UpdateStrategy updatestrategy;
};
#define BACKUP_MANGA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&backup_manga__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, 0,NULL, 0,NULL, 0,NULL, 0, 0, 0,NULL, 0, 0,NULL, UPDATE_STRATEGY__ALWAYS_UPDATE }


/* BackupManga methods */
void   backup_manga__init
                     (BackupManga         *message);
size_t backup_manga__get_packed_size
                     (const BackupManga   *message);
size_t backup_manga__pack
                     (const BackupManga   *message,
                      uint8_t             *out);
size_t backup_manga__pack_to_buffer
                     (const BackupManga   *message,
                      ProtobufCBuffer     *buffer);
BackupManga *
       backup_manga__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   backup_manga__free_unpacked
                     (BackupManga *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*BackupManga_Closure)
                 (const BackupManga *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor backup_manga__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_backup_5fmanga_2eproto__INCLUDED */
