/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backup_preference.proto */

#ifndef PROTOBUF_C_backup_5fpreference_2eproto__INCLUDED
#define PROTOBUF_C_backup_5fpreference_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct BackupPreference BackupPreference;
typedef struct BackupSourcePreferences BackupSourcePreferences;
typedef struct PreferenceValue PreferenceValue;
typedef struct IntPreferenceValue IntPreferenceValue;
typedef struct LongPreferenceValue LongPreferenceValue;
typedef struct FloatPreferenceValue FloatPreferenceValue;
typedef struct StringPreferenceValue StringPreferenceValue;
typedef struct BooleanPreferenceValue BooleanPreferenceValue;
typedef struct StringSetPreferenceValue StringSetPreferenceValue;


/* --- enums --- */


/* --- messages --- */

struct  BackupPreference
{
  ProtobufCMessage base;
  char *key;
  PreferenceValue *value;
};
#define BACKUP_PREFERENCE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&backup_preference__descriptor) \
, (char *)protobuf_c_empty_string, NULL }


struct  BackupSourcePreferences
{
  ProtobufCMessage base;
  char *source_key;
  size_t n_prefs;
  BackupPreference **prefs;
};
#define BACKUP_SOURCE_PREFERENCES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&backup_source_preferences__descriptor) \
, (char *)protobuf_c_empty_string, 0,NULL }


typedef enum {
  PREFERENCE_VALUE__VALUE__NOT_SET = 0,
  PREFERENCE_VALUE__VALUE_INT_VALUE = 1,
  PREFERENCE_VALUE__VALUE_LONG_VALUE = 2,
  PREFERENCE_VALUE__VALUE_FLOAT_VALUE = 3,
  PREFERENCE_VALUE__VALUE_STRING_VALUE = 4,
  PREFERENCE_VALUE__VALUE_BOOLEAN_VALUE = 5,
  PREFERENCE_VALUE__VALUE_STRING_SET_VALUE = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PREFERENCE_VALUE__VALUE__CASE)
} PreferenceValue__ValueCase;

struct  PreferenceValue
{
  ProtobufCMessage base;
  PreferenceValue__ValueCase value_case;
  union {
    IntPreferenceValue *int_value;
    LongPreferenceValue *long_value;
    FloatPreferenceValue *float_value;
    StringPreferenceValue *string_value;
    BooleanPreferenceValue *boolean_value;
    StringSetPreferenceValue *string_set_value;
  };
};
#define PREFERENCE_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&preference_value__descriptor) \
, PREFERENCE_VALUE__VALUE__NOT_SET, {0} }


struct  IntPreferenceValue
{
  ProtobufCMessage base;
  int32_t value;
};
#define INT_PREFERENCE_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&int_preference_value__descriptor) \
, 0 }


struct  LongPreferenceValue
{
  ProtobufCMessage base;
  int64_t value;
};
#define LONG_PREFERENCE_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&long_preference_value__descriptor) \
, 0 }


struct  FloatPreferenceValue
{
  ProtobufCMessage base;
  float value;
};
#define FLOAT_PREFERENCE_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&float_preference_value__descriptor) \
, 0 }


struct  StringPreferenceValue
{
  ProtobufCMessage base;
  char *value;
};
#define STRING_PREFERENCE_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&string_preference_value__descriptor) \
, (char *)protobuf_c_empty_string }


struct  BooleanPreferenceValue
{
  ProtobufCMessage base;
  protobuf_c_boolean value;
};
#define BOOLEAN_PREFERENCE_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&boolean_preference_value__descriptor) \
, 0 }


struct  StringSetPreferenceValue
{
  ProtobufCMessage base;
  size_t n_value;
  char **value;
};
#define STRING_SET_PREFERENCE_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&string_set_preference_value__descriptor) \
, 0,NULL }


/* BackupPreference methods */
void   backup_preference__init
                     (BackupPreference         *message);
size_t backup_preference__get_packed_size
                     (const BackupPreference   *message);
size_t backup_preference__pack
                     (const BackupPreference   *message,
                      uint8_t             *out);
size_t backup_preference__pack_to_buffer
                     (const BackupPreference   *message,
                      ProtobufCBuffer     *buffer);
BackupPreference *
       backup_preference__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   backup_preference__free_unpacked
                     (BackupPreference *message,
                      ProtobufCAllocator *allocator);
/* BackupSourcePreferences methods */
void   backup_source_preferences__init
                     (BackupSourcePreferences         *message);
size_t backup_source_preferences__get_packed_size
                     (const BackupSourcePreferences   *message);
size_t backup_source_preferences__pack
                     (const BackupSourcePreferences   *message,
                      uint8_t             *out);
size_t backup_source_preferences__pack_to_buffer
                     (const BackupSourcePreferences   *message,
                      ProtobufCBuffer     *buffer);
BackupSourcePreferences *
       backup_source_preferences__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   backup_source_preferences__free_unpacked
                     (BackupSourcePreferences *message,
                      ProtobufCAllocator *allocator);
/* PreferenceValue methods */
void   preference_value__init
                     (PreferenceValue         *message);
size_t preference_value__get_packed_size
                     (const PreferenceValue   *message);
size_t preference_value__pack
                     (const PreferenceValue   *message,
                      uint8_t             *out);
size_t preference_value__pack_to_buffer
                     (const PreferenceValue   *message,
                      ProtobufCBuffer     *buffer);
PreferenceValue *
       preference_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   preference_value__free_unpacked
                     (PreferenceValue *message,
                      ProtobufCAllocator *allocator);
/* IntPreferenceValue methods */
void   int_preference_value__init
                     (IntPreferenceValue         *message);
size_t int_preference_value__get_packed_size
                     (const IntPreferenceValue   *message);
size_t int_preference_value__pack
                     (const IntPreferenceValue   *message,
                      uint8_t             *out);
size_t int_preference_value__pack_to_buffer
                     (const IntPreferenceValue   *message,
                      ProtobufCBuffer     *buffer);
IntPreferenceValue *
       int_preference_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   int_preference_value__free_unpacked
                     (IntPreferenceValue *message,
                      ProtobufCAllocator *allocator);
/* LongPreferenceValue methods */
void   long_preference_value__init
                     (LongPreferenceValue         *message);
size_t long_preference_value__get_packed_size
                     (const LongPreferenceValue   *message);
size_t long_preference_value__pack
                     (const LongPreferenceValue   *message,
                      uint8_t             *out);
size_t long_preference_value__pack_to_buffer
                     (const LongPreferenceValue   *message,
                      ProtobufCBuffer     *buffer);
LongPreferenceValue *
       long_preference_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   long_preference_value__free_unpacked
                     (LongPreferenceValue *message,
                      ProtobufCAllocator *allocator);
/* FloatPreferenceValue methods */
void   float_preference_value__init
                     (FloatPreferenceValue         *message);
size_t float_preference_value__get_packed_size
                     (const FloatPreferenceValue   *message);
size_t float_preference_value__pack
                     (const FloatPreferenceValue   *message,
                      uint8_t             *out);
size_t float_preference_value__pack_to_buffer
                     (const FloatPreferenceValue   *message,
                      ProtobufCBuffer     *buffer);
FloatPreferenceValue *
       float_preference_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   float_preference_value__free_unpacked
                     (FloatPreferenceValue *message,
                      ProtobufCAllocator *allocator);
/* StringPreferenceValue methods */
void   string_preference_value__init
                     (StringPreferenceValue         *message);
size_t string_preference_value__get_packed_size
                     (const StringPreferenceValue   *message);
size_t string_preference_value__pack
                     (const StringPreferenceValue   *message,
                      uint8_t             *out);
size_t string_preference_value__pack_to_buffer
                     (const StringPreferenceValue   *message,
                      ProtobufCBuffer     *buffer);
StringPreferenceValue *
       string_preference_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   string_preference_value__free_unpacked
                     (StringPreferenceValue *message,
                      ProtobufCAllocator *allocator);
/* BooleanPreferenceValue methods */
void   boolean_preference_value__init
                     (BooleanPreferenceValue         *message);
size_t boolean_preference_value__get_packed_size
                     (const BooleanPreferenceValue   *message);
size_t boolean_preference_value__pack
                     (const BooleanPreferenceValue   *message,
                      uint8_t             *out);
size_t boolean_preference_value__pack_to_buffer
                     (const BooleanPreferenceValue   *message,
                      ProtobufCBuffer     *buffer);
BooleanPreferenceValue *
       boolean_preference_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   boolean_preference_value__free_unpacked
                     (BooleanPreferenceValue *message,
                      ProtobufCAllocator *allocator);
/* StringSetPreferenceValue methods */
void   string_set_preference_value__init
                     (StringSetPreferenceValue         *message);
size_t string_set_preference_value__get_packed_size
                     (const StringSetPreferenceValue   *message);
size_t string_set_preference_value__pack
                     (const StringSetPreferenceValue   *message,
                      uint8_t             *out);
size_t string_set_preference_value__pack_to_buffer
                     (const StringSetPreferenceValue   *message,
                      ProtobufCBuffer     *buffer);
StringSetPreferenceValue *
       string_set_preference_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   string_set_preference_value__free_unpacked
                     (StringSetPreferenceValue *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*BackupPreference_Closure)
                 (const BackupPreference *message,
                  void *closure_data);
typedef void (*BackupSourcePreferences_Closure)
                 (const BackupSourcePreferences *message,
                  void *closure_data);
typedef void (*PreferenceValue_Closure)
                 (const PreferenceValue *message,
                  void *closure_data);
typedef void (*IntPreferenceValue_Closure)
                 (const IntPreferenceValue *message,
                  void *closure_data);
typedef void (*LongPreferenceValue_Closure)
                 (const LongPreferenceValue *message,
                  void *closure_data);
typedef void (*FloatPreferenceValue_Closure)
                 (const FloatPreferenceValue *message,
                  void *closure_data);
typedef void (*StringPreferenceValue_Closure)
                 (const StringPreferenceValue *message,
                  void *closure_data);
typedef void (*BooleanPreferenceValue_Closure)
                 (const BooleanPreferenceValue *message,
                  void *closure_data);
typedef void (*StringSetPreferenceValue_Closure)
                 (const StringSetPreferenceValue *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor backup_preference__descriptor;
extern const ProtobufCMessageDescriptor backup_source_preferences__descriptor;
extern const ProtobufCMessageDescriptor preference_value__descriptor;
extern const ProtobufCMessageDescriptor int_preference_value__descriptor;
extern const ProtobufCMessageDescriptor long_preference_value__descriptor;
extern const ProtobufCMessageDescriptor float_preference_value__descriptor;
extern const ProtobufCMessageDescriptor string_preference_value__descriptor;
extern const ProtobufCMessageDescriptor boolean_preference_value__descriptor;
extern const ProtobufCMessageDescriptor string_set_preference_value__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_backup_5fpreference_2eproto__INCLUDED */
