/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: manga_update_strategy.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "manga_update_strategy.pb-c.h"
static const ProtobufCEnumValue update_strategy__enum_values_by_number[2] =
{
  { "ALWAYS_UPDATE", "UPDATE_STRATEGY__ALWAYS_UPDATE", 0 },
  { "ONLY_FETCH_ONCE", "UPDATE_STRATEGY__ONLY_FETCH_ONCE", 1 },
};
static const ProtobufCIntRange update_strategy__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex update_strategy__enum_values_by_name[2] =
{
  { "ALWAYS_UPDATE", 0 },
  { "ONLY_FETCH_ONCE", 1 },
};
const ProtobufCEnumDescriptor update_strategy__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "UpdateStrategy",
  "UpdateStrategy",
  "UpdateStrategy",
  "",
  2,
  update_strategy__enum_values_by_number,
  2,
  update_strategy__enum_values_by_name,
  1,
  update_strategy__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
