// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backup_history.proto
// Protobuf C++ Version: 4.25.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_backup_5fhistory_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_backup_5fhistory_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_backup_5fhistory_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_backup_5fhistory_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_backup_5fhistory_2eproto;
class BackupHistory;
struct BackupHistoryDefaultTypeInternal;
extern BackupHistoryDefaultTypeInternal _BackupHistory_default_instance_;
class BrokenBackupHistory;
struct BrokenBackupHistoryDefaultTypeInternal;
extern BrokenBackupHistoryDefaultTypeInternal _BrokenBackupHistory_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class BrokenBackupHistory final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BrokenBackupHistory) */ {
 public:
  inline BrokenBackupHistory() : BrokenBackupHistory(nullptr) {}
  ~BrokenBackupHistory() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR BrokenBackupHistory(::google::protobuf::internal::ConstantInitialized);

  inline BrokenBackupHistory(const BrokenBackupHistory& from)
      : BrokenBackupHistory(nullptr, from) {}
  BrokenBackupHistory(BrokenBackupHistory&& from) noexcept
    : BrokenBackupHistory() {
    *this = ::std::move(from);
  }

  inline BrokenBackupHistory& operator=(const BrokenBackupHistory& from) {
    CopyFrom(from);
    return *this;
  }
  inline BrokenBackupHistory& operator=(BrokenBackupHistory&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BrokenBackupHistory& default_instance() {
    return *internal_default_instance();
  }
  static inline const BrokenBackupHistory* internal_default_instance() {
    return reinterpret_cast<const BrokenBackupHistory*>(
               &_BrokenBackupHistory_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BrokenBackupHistory& a, BrokenBackupHistory& b) {
    a.Swap(&b);
  }
  inline void Swap(BrokenBackupHistory* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BrokenBackupHistory* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BrokenBackupHistory* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BrokenBackupHistory>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BrokenBackupHistory& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const BrokenBackupHistory& from) {
    BrokenBackupHistory::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(BrokenBackupHistory* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "BrokenBackupHistory";
  }
  protected:
  explicit BrokenBackupHistory(::google::protobuf::Arena* arena);
  BrokenBackupHistory(::google::protobuf::Arena* arena, const BrokenBackupHistory& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUrlFieldNumber = 1,
    kLastReadFieldNumber = 2,
    kReadDurationFieldNumber = 3,
  };
  // string url = 1;
  void clear_url() ;
  const std::string& url() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_url(Arg_&& arg, Args_... args);
  std::string* mutable_url();
  PROTOBUF_NODISCARD std::string* release_url();
  void set_allocated_url(std::string* value);

  private:
  const std::string& _internal_url() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_url(
      const std::string& value);
  std::string* _internal_mutable_url();

  public:
  // int64 lastRead = 2;
  void clear_lastread() ;
  ::int64_t lastread() const;
  void set_lastread(::int64_t value);

  private:
  ::int64_t _internal_lastread() const;
  void _internal_set_lastread(::int64_t value);

  public:
  // int64 readDuration = 3;
  void clear_readduration() ;
  ::int64_t readduration() const;
  void set_readduration(::int64_t value);

  private:
  ::int64_t _internal_readduration() const;
  void _internal_set_readduration(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:BrokenBackupHistory)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      31, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr url_;
    ::int64_t lastread_;
    ::int64_t readduration_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_backup_5fhistory_2eproto;
};// -------------------------------------------------------------------

class BackupHistory final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BackupHistory) */ {
 public:
  inline BackupHistory() : BackupHistory(nullptr) {}
  ~BackupHistory() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR BackupHistory(::google::protobuf::internal::ConstantInitialized);

  inline BackupHistory(const BackupHistory& from)
      : BackupHistory(nullptr, from) {}
  BackupHistory(BackupHistory&& from) noexcept
    : BackupHistory() {
    *this = ::std::move(from);
  }

  inline BackupHistory& operator=(const BackupHistory& from) {
    CopyFrom(from);
    return *this;
  }
  inline BackupHistory& operator=(BackupHistory&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BackupHistory& default_instance() {
    return *internal_default_instance();
  }
  static inline const BackupHistory* internal_default_instance() {
    return reinterpret_cast<const BackupHistory*>(
               &_BackupHistory_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BackupHistory& a, BackupHistory& b) {
    a.Swap(&b);
  }
  inline void Swap(BackupHistory* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BackupHistory* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BackupHistory* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BackupHistory>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BackupHistory& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const BackupHistory& from) {
    BackupHistory::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(BackupHistory* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "BackupHistory";
  }
  protected:
  explicit BackupHistory(::google::protobuf::Arena* arena);
  BackupHistory(::google::protobuf::Arena* arena, const BackupHistory& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUrlFieldNumber = 1,
    kLastReadFieldNumber = 2,
    kReadDurationFieldNumber = 3,
  };
  // string url = 1;
  void clear_url() ;
  const std::string& url() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_url(Arg_&& arg, Args_... args);
  std::string* mutable_url();
  PROTOBUF_NODISCARD std::string* release_url();
  void set_allocated_url(std::string* value);

  private:
  const std::string& _internal_url() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_url(
      const std::string& value);
  std::string* _internal_mutable_url();

  public:
  // int64 lastRead = 2;
  void clear_lastread() ;
  ::int64_t lastread() const;
  void set_lastread(::int64_t value);

  private:
  ::int64_t _internal_lastread() const;
  void _internal_set_lastread(::int64_t value);

  public:
  // int64 readDuration = 3;
  void clear_readduration() ;
  ::int64_t readduration() const;
  void set_readduration(::int64_t value);

  private:
  ::int64_t _internal_readduration() const;
  void _internal_set_readduration(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:BackupHistory)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      25, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr url_;
    ::int64_t lastread_;
    ::int64_t readduration_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_backup_5fhistory_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BrokenBackupHistory

// string url = 1;
inline void BrokenBackupHistory::clear_url() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.url_.ClearToEmpty();
}
inline const std::string& BrokenBackupHistory::url() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:BrokenBackupHistory.url)
  return _internal_url();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void BrokenBackupHistory::set_url(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.url_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:BrokenBackupHistory.url)
}
inline std::string* BrokenBackupHistory::mutable_url() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_url();
  // @@protoc_insertion_point(field_mutable:BrokenBackupHistory.url)
  return _s;
}
inline const std::string& BrokenBackupHistory::_internal_url() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.url_.Get();
}
inline void BrokenBackupHistory::_internal_set_url(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.url_.Set(value, GetArena());
}
inline std::string* BrokenBackupHistory::_internal_mutable_url() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.url_.Mutable( GetArena());
}
inline std::string* BrokenBackupHistory::release_url() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:BrokenBackupHistory.url)
  return _impl_.url_.Release();
}
inline void BrokenBackupHistory::set_allocated_url(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.url_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.url_.IsDefault()) {
          _impl_.url_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:BrokenBackupHistory.url)
}

// int64 lastRead = 2;
inline void BrokenBackupHistory::clear_lastread() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.lastread_ = ::int64_t{0};
}
inline ::int64_t BrokenBackupHistory::lastread() const {
  // @@protoc_insertion_point(field_get:BrokenBackupHistory.lastRead)
  return _internal_lastread();
}
inline void BrokenBackupHistory::set_lastread(::int64_t value) {
  _internal_set_lastread(value);
  // @@protoc_insertion_point(field_set:BrokenBackupHistory.lastRead)
}
inline ::int64_t BrokenBackupHistory::_internal_lastread() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.lastread_;
}
inline void BrokenBackupHistory::_internal_set_lastread(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.lastread_ = value;
}

// int64 readDuration = 3;
inline void BrokenBackupHistory::clear_readduration() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.readduration_ = ::int64_t{0};
}
inline ::int64_t BrokenBackupHistory::readduration() const {
  // @@protoc_insertion_point(field_get:BrokenBackupHistory.readDuration)
  return _internal_readduration();
}
inline void BrokenBackupHistory::set_readduration(::int64_t value) {
  _internal_set_readduration(value);
  // @@protoc_insertion_point(field_set:BrokenBackupHistory.readDuration)
}
inline ::int64_t BrokenBackupHistory::_internal_readduration() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.readduration_;
}
inline void BrokenBackupHistory::_internal_set_readduration(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.readduration_ = value;
}

// -------------------------------------------------------------------

// BackupHistory

// string url = 1;
inline void BackupHistory::clear_url() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.url_.ClearToEmpty();
}
inline const std::string& BackupHistory::url() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:BackupHistory.url)
  return _internal_url();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void BackupHistory::set_url(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.url_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:BackupHistory.url)
}
inline std::string* BackupHistory::mutable_url() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_url();
  // @@protoc_insertion_point(field_mutable:BackupHistory.url)
  return _s;
}
inline const std::string& BackupHistory::_internal_url() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.url_.Get();
}
inline void BackupHistory::_internal_set_url(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.url_.Set(value, GetArena());
}
inline std::string* BackupHistory::_internal_mutable_url() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.url_.Mutable( GetArena());
}
inline std::string* BackupHistory::release_url() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:BackupHistory.url)
  return _impl_.url_.Release();
}
inline void BackupHistory::set_allocated_url(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.url_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.url_.IsDefault()) {
          _impl_.url_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:BackupHistory.url)
}

// int64 lastRead = 2;
inline void BackupHistory::clear_lastread() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.lastread_ = ::int64_t{0};
}
inline ::int64_t BackupHistory::lastread() const {
  // @@protoc_insertion_point(field_get:BackupHistory.lastRead)
  return _internal_lastread();
}
inline void BackupHistory::set_lastread(::int64_t value) {
  _internal_set_lastread(value);
  // @@protoc_insertion_point(field_set:BackupHistory.lastRead)
}
inline ::int64_t BackupHistory::_internal_lastread() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.lastread_;
}
inline void BackupHistory::_internal_set_lastread(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.lastread_ = value;
}

// int64 readDuration = 3;
inline void BackupHistory::clear_readduration() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.readduration_ = ::int64_t{0};
}
inline ::int64_t BackupHistory::readduration() const {
  // @@protoc_insertion_point(field_get:BackupHistory.readDuration)
  return _internal_readduration();
}
inline void BackupHistory::set_readduration(::int64_t value) {
  _internal_set_readduration(value);
  // @@protoc_insertion_point(field_set:BackupHistory.readDuration)
}
inline ::int64_t BackupHistory::_internal_readduration() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.readduration_;
}
inline void BackupHistory::_internal_set_readduration(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.readduration_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_backup_5fhistory_2eproto_2epb_2eh
