// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tachiyomi.proto
// Protobuf C++ Version: 5.28.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_tachiyomi_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_tachiyomi_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "backup_category.pb.h"
#include "backup_manga.pb.h"
#include "backup_preference.pb.h"
#include "backup_source.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_tachiyomi_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_tachiyomi_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_tachiyomi_2eproto;
class Backup;
struct BackupDefaultTypeInternal;
extern BackupDefaultTypeInternal _Backup_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Backup final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Backup) */ {
 public:
  inline Backup() : Backup(nullptr) {}
  ~Backup() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Backup(
      ::google::protobuf::internal::ConstantInitialized);

  inline Backup(const Backup& from) : Backup(nullptr, from) {}
  inline Backup(Backup&& from) noexcept
      : Backup(nullptr, std::move(from)) {}
  inline Backup& operator=(const Backup& from) {
    CopyFrom(from);
    return *this;
  }
  inline Backup& operator=(Backup&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Backup& default_instance() {
    return *internal_default_instance();
  }
  static inline const Backup* internal_default_instance() {
    return reinterpret_cast<const Backup*>(
        &_Backup_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Backup& a, Backup& b) { a.Swap(&b); }
  inline void Swap(Backup* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Backup* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Backup* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Backup>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Backup& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Backup& from) { Backup::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Backup* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Backup"; }

 protected:
  explicit Backup(::google::protobuf::Arena* arena);
  Backup(::google::protobuf::Arena* arena, const Backup& from);
  Backup(::google::protobuf::Arena* arena, Backup&& from) noexcept
      : Backup(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMangaBackupFieldNumber = 1,
    kCategoriesFieldNumber = 2,
    kBrokenSourcesFieldNumber = 100,
    kSourcesFieldNumber = 101,
    kPreferencesFieldNumber = 104,
    kSourcePreferencesFieldNumber = 105,
  };
  // repeated .BackupManga mangaBackup = 1;
  int mangabackup_size() const;
  private:
  int _internal_mangabackup_size() const;

  public:
  void clear_mangabackup() ;
  ::BackupManga* mutable_mangabackup(int index);
  ::google::protobuf::RepeatedPtrField<::BackupManga>* mutable_mangabackup();

  private:
  const ::google::protobuf::RepeatedPtrField<::BackupManga>& _internal_mangabackup() const;
  ::google::protobuf::RepeatedPtrField<::BackupManga>* _internal_mutable_mangabackup();
  public:
  const ::BackupManga& mangabackup(int index) const;
  ::BackupManga* add_mangabackup();
  const ::google::protobuf::RepeatedPtrField<::BackupManga>& mangabackup() const;
  // repeated .BackupCategory categories = 2;
  int categories_size() const;
  private:
  int _internal_categories_size() const;

  public:
  void clear_categories() ;
  ::BackupCategory* mutable_categories(int index);
  ::google::protobuf::RepeatedPtrField<::BackupCategory>* mutable_categories();

  private:
  const ::google::protobuf::RepeatedPtrField<::BackupCategory>& _internal_categories() const;
  ::google::protobuf::RepeatedPtrField<::BackupCategory>* _internal_mutable_categories();
  public:
  const ::BackupCategory& categories(int index) const;
  ::BackupCategory* add_categories();
  const ::google::protobuf::RepeatedPtrField<::BackupCategory>& categories() const;
  // repeated .BrokenBackupSource brokenSources = 100;
  int brokensources_size() const;
  private:
  int _internal_brokensources_size() const;

  public:
  void clear_brokensources() ;
  ::BrokenBackupSource* mutable_brokensources(int index);
  ::google::protobuf::RepeatedPtrField<::BrokenBackupSource>* mutable_brokensources();

  private:
  const ::google::protobuf::RepeatedPtrField<::BrokenBackupSource>& _internal_brokensources() const;
  ::google::protobuf::RepeatedPtrField<::BrokenBackupSource>* _internal_mutable_brokensources();
  public:
  const ::BrokenBackupSource& brokensources(int index) const;
  ::BrokenBackupSource* add_brokensources();
  const ::google::protobuf::RepeatedPtrField<::BrokenBackupSource>& brokensources() const;
  // repeated .BackupSource sources = 101;
  int sources_size() const;
  private:
  int _internal_sources_size() const;

  public:
  void clear_sources() ;
  ::BackupSource* mutable_sources(int index);
  ::google::protobuf::RepeatedPtrField<::BackupSource>* mutable_sources();

  private:
  const ::google::protobuf::RepeatedPtrField<::BackupSource>& _internal_sources() const;
  ::google::protobuf::RepeatedPtrField<::BackupSource>* _internal_mutable_sources();
  public:
  const ::BackupSource& sources(int index) const;
  ::BackupSource* add_sources();
  const ::google::protobuf::RepeatedPtrField<::BackupSource>& sources() const;
  // repeated .BackupPreference preferences = 104;
  int preferences_size() const;
  private:
  int _internal_preferences_size() const;

  public:
  void clear_preferences() ;
  ::BackupPreference* mutable_preferences(int index);
  ::google::protobuf::RepeatedPtrField<::BackupPreference>* mutable_preferences();

  private:
  const ::google::protobuf::RepeatedPtrField<::BackupPreference>& _internal_preferences() const;
  ::google::protobuf::RepeatedPtrField<::BackupPreference>* _internal_mutable_preferences();
  public:
  const ::BackupPreference& preferences(int index) const;
  ::BackupPreference* add_preferences();
  const ::google::protobuf::RepeatedPtrField<::BackupPreference>& preferences() const;
  // repeated .BackupSourcePreferences sourcePreferences = 105;
  int sourcepreferences_size() const;
  private:
  int _internal_sourcepreferences_size() const;

  public:
  void clear_sourcepreferences() ;
  ::BackupSourcePreferences* mutable_sourcepreferences(int index);
  ::google::protobuf::RepeatedPtrField<::BackupSourcePreferences>* mutable_sourcepreferences();

  private:
  const ::google::protobuf::RepeatedPtrField<::BackupSourcePreferences>& _internal_sourcepreferences() const;
  ::google::protobuf::RepeatedPtrField<::BackupSourcePreferences>* _internal_mutable_sourcepreferences();
  public:
  const ::BackupSourcePreferences& sourcepreferences(int index) const;
  ::BackupSourcePreferences* add_sourcepreferences();
  const ::google::protobuf::RepeatedPtrField<::BackupSourcePreferences>& sourcepreferences() const;
  // @@protoc_insertion_point(class_scope:Backup)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 6,
      0, 7>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Backup_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Backup& from_msg);
    ::google::protobuf::RepeatedPtrField< ::BackupManga > mangabackup_;
    ::google::protobuf::RepeatedPtrField< ::BackupCategory > categories_;
    ::google::protobuf::RepeatedPtrField< ::BrokenBackupSource > brokensources_;
    ::google::protobuf::RepeatedPtrField< ::BackupSource > sources_;
    ::google::protobuf::RepeatedPtrField< ::BackupPreference > preferences_;
    ::google::protobuf::RepeatedPtrField< ::BackupSourcePreferences > sourcepreferences_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tachiyomi_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Backup

// repeated .BackupManga mangaBackup = 1;
inline int Backup::_internal_mangabackup_size() const {
  return _internal_mangabackup().size();
}
inline int Backup::mangabackup_size() const {
  return _internal_mangabackup_size();
}
inline ::BackupManga* Backup::mutable_mangabackup(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Backup.mangaBackup)
  return _internal_mutable_mangabackup()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::BackupManga>* Backup::mutable_mangabackup()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Backup.mangaBackup)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_mangabackup();
}
inline const ::BackupManga& Backup::mangabackup(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Backup.mangaBackup)
  return _internal_mangabackup().Get(index);
}
inline ::BackupManga* Backup::add_mangabackup() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::BackupManga* _add = _internal_mutable_mangabackup()->Add();
  // @@protoc_insertion_point(field_add:Backup.mangaBackup)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::BackupManga>& Backup::mangabackup() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Backup.mangaBackup)
  return _internal_mangabackup();
}
inline const ::google::protobuf::RepeatedPtrField<::BackupManga>&
Backup::_internal_mangabackup() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mangabackup_;
}
inline ::google::protobuf::RepeatedPtrField<::BackupManga>*
Backup::_internal_mutable_mangabackup() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.mangabackup_;
}

// repeated .BackupCategory categories = 2;
inline int Backup::_internal_categories_size() const {
  return _internal_categories().size();
}
inline int Backup::categories_size() const {
  return _internal_categories_size();
}
inline ::BackupCategory* Backup::mutable_categories(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Backup.categories)
  return _internal_mutable_categories()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::BackupCategory>* Backup::mutable_categories()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Backup.categories)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_categories();
}
inline const ::BackupCategory& Backup::categories(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Backup.categories)
  return _internal_categories().Get(index);
}
inline ::BackupCategory* Backup::add_categories() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::BackupCategory* _add = _internal_mutable_categories()->Add();
  // @@protoc_insertion_point(field_add:Backup.categories)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::BackupCategory>& Backup::categories() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Backup.categories)
  return _internal_categories();
}
inline const ::google::protobuf::RepeatedPtrField<::BackupCategory>&
Backup::_internal_categories() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.categories_;
}
inline ::google::protobuf::RepeatedPtrField<::BackupCategory>*
Backup::_internal_mutable_categories() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.categories_;
}

// repeated .BrokenBackupSource brokenSources = 100;
inline int Backup::_internal_brokensources_size() const {
  return _internal_brokensources().size();
}
inline int Backup::brokensources_size() const {
  return _internal_brokensources_size();
}
inline ::BrokenBackupSource* Backup::mutable_brokensources(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Backup.brokenSources)
  return _internal_mutable_brokensources()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::BrokenBackupSource>* Backup::mutable_brokensources()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Backup.brokenSources)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_brokensources();
}
inline const ::BrokenBackupSource& Backup::brokensources(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Backup.brokenSources)
  return _internal_brokensources().Get(index);
}
inline ::BrokenBackupSource* Backup::add_brokensources() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::BrokenBackupSource* _add = _internal_mutable_brokensources()->Add();
  // @@protoc_insertion_point(field_add:Backup.brokenSources)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::BrokenBackupSource>& Backup::brokensources() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Backup.brokenSources)
  return _internal_brokensources();
}
inline const ::google::protobuf::RepeatedPtrField<::BrokenBackupSource>&
Backup::_internal_brokensources() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.brokensources_;
}
inline ::google::protobuf::RepeatedPtrField<::BrokenBackupSource>*
Backup::_internal_mutable_brokensources() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.brokensources_;
}

// repeated .BackupSource sources = 101;
inline int Backup::_internal_sources_size() const {
  return _internal_sources().size();
}
inline int Backup::sources_size() const {
  return _internal_sources_size();
}
inline ::BackupSource* Backup::mutable_sources(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Backup.sources)
  return _internal_mutable_sources()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::BackupSource>* Backup::mutable_sources()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Backup.sources)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_sources();
}
inline const ::BackupSource& Backup::sources(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Backup.sources)
  return _internal_sources().Get(index);
}
inline ::BackupSource* Backup::add_sources() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::BackupSource* _add = _internal_mutable_sources()->Add();
  // @@protoc_insertion_point(field_add:Backup.sources)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::BackupSource>& Backup::sources() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Backup.sources)
  return _internal_sources();
}
inline const ::google::protobuf::RepeatedPtrField<::BackupSource>&
Backup::_internal_sources() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sources_;
}
inline ::google::protobuf::RepeatedPtrField<::BackupSource>*
Backup::_internal_mutable_sources() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.sources_;
}

// repeated .BackupPreference preferences = 104;
inline int Backup::_internal_preferences_size() const {
  return _internal_preferences().size();
}
inline int Backup::preferences_size() const {
  return _internal_preferences_size();
}
inline ::BackupPreference* Backup::mutable_preferences(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Backup.preferences)
  return _internal_mutable_preferences()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::BackupPreference>* Backup::mutable_preferences()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Backup.preferences)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_preferences();
}
inline const ::BackupPreference& Backup::preferences(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Backup.preferences)
  return _internal_preferences().Get(index);
}
inline ::BackupPreference* Backup::add_preferences() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::BackupPreference* _add = _internal_mutable_preferences()->Add();
  // @@protoc_insertion_point(field_add:Backup.preferences)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::BackupPreference>& Backup::preferences() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Backup.preferences)
  return _internal_preferences();
}
inline const ::google::protobuf::RepeatedPtrField<::BackupPreference>&
Backup::_internal_preferences() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.preferences_;
}
inline ::google::protobuf::RepeatedPtrField<::BackupPreference>*
Backup::_internal_mutable_preferences() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.preferences_;
}

// repeated .BackupSourcePreferences sourcePreferences = 105;
inline int Backup::_internal_sourcepreferences_size() const {
  return _internal_sourcepreferences().size();
}
inline int Backup::sourcepreferences_size() const {
  return _internal_sourcepreferences_size();
}
inline ::BackupSourcePreferences* Backup::mutable_sourcepreferences(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Backup.sourcePreferences)
  return _internal_mutable_sourcepreferences()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::BackupSourcePreferences>* Backup::mutable_sourcepreferences()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Backup.sourcePreferences)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_sourcepreferences();
}
inline const ::BackupSourcePreferences& Backup::sourcepreferences(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Backup.sourcePreferences)
  return _internal_sourcepreferences().Get(index);
}
inline ::BackupSourcePreferences* Backup::add_sourcepreferences() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::BackupSourcePreferences* _add = _internal_mutable_sourcepreferences()->Add();
  // @@protoc_insertion_point(field_add:Backup.sourcePreferences)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::BackupSourcePreferences>& Backup::sourcepreferences() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Backup.sourcePreferences)
  return _internal_sourcepreferences();
}
inline const ::google::protobuf::RepeatedPtrField<::BackupSourcePreferences>&
Backup::_internal_sourcepreferences() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sourcepreferences_;
}
inline ::google::protobuf::RepeatedPtrField<::BackupSourcePreferences>*
Backup::_internal_mutable_sourcepreferences() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.sourcepreferences_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_tachiyomi_2eproto_2epb_2eh
