// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backup_preference.proto

#include "backup_preference.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr StringSetPreferenceValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StringSetPreferenceValue::StringSetPreferenceValue(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct StringSetPreferenceValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StringSetPreferenceValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StringSetPreferenceValueDefaultTypeInternal() {}
  union {
    StringSetPreferenceValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StringSetPreferenceValueDefaultTypeInternal _StringSetPreferenceValue_default_instance_;

inline constexpr StringPreferenceValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StringPreferenceValue::StringPreferenceValue(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct StringPreferenceValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StringPreferenceValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StringPreferenceValueDefaultTypeInternal() {}
  union {
    StringPreferenceValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StringPreferenceValueDefaultTypeInternal _StringPreferenceValue_default_instance_;

inline constexpr LongPreferenceValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LongPreferenceValue::LongPreferenceValue(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LongPreferenceValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LongPreferenceValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LongPreferenceValueDefaultTypeInternal() {}
  union {
    LongPreferenceValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LongPreferenceValueDefaultTypeInternal _LongPreferenceValue_default_instance_;

inline constexpr IntPreferenceValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR IntPreferenceValue::IntPreferenceValue(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct IntPreferenceValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IntPreferenceValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IntPreferenceValueDefaultTypeInternal() {}
  union {
    IntPreferenceValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IntPreferenceValueDefaultTypeInternal _IntPreferenceValue_default_instance_;

inline constexpr FloatPreferenceValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FloatPreferenceValue::FloatPreferenceValue(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FloatPreferenceValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FloatPreferenceValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FloatPreferenceValueDefaultTypeInternal() {}
  union {
    FloatPreferenceValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FloatPreferenceValueDefaultTypeInternal _FloatPreferenceValue_default_instance_;

inline constexpr BooleanPreferenceValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BooleanPreferenceValue::BooleanPreferenceValue(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct BooleanPreferenceValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BooleanPreferenceValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BooleanPreferenceValueDefaultTypeInternal() {}
  union {
    BooleanPreferenceValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BooleanPreferenceValueDefaultTypeInternal _BooleanPreferenceValue_default_instance_;

inline constexpr PreferenceValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR PreferenceValue::PreferenceValue(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PreferenceValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PreferenceValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PreferenceValueDefaultTypeInternal() {}
  union {
    PreferenceValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PreferenceValueDefaultTypeInternal _PreferenceValue_default_instance_;

inline constexpr BackupPreference::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR BackupPreference::BackupPreference(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct BackupPreferenceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BackupPreferenceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BackupPreferenceDefaultTypeInternal() {}
  union {
    BackupPreference _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BackupPreferenceDefaultTypeInternal _BackupPreference_default_instance_;

inline constexpr BackupSourcePreferences::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : prefs_{},
        source_key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BackupSourcePreferences::BackupSourcePreferences(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct BackupSourcePreferencesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BackupSourcePreferencesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BackupSourcePreferencesDefaultTypeInternal() {}
  union {
    BackupSourcePreferences _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BackupSourcePreferencesDefaultTypeInternal _BackupSourcePreferences_default_instance_;
static ::_pb::Metadata file_level_metadata_backup_5fpreference_2eproto[9];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_backup_5fpreference_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_backup_5fpreference_2eproto = nullptr;
const ::uint32_t TableStruct_backup_5fpreference_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::BackupPreference, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::BackupPreference, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::BackupPreference, _impl_.key_),
    PROTOBUF_FIELD_OFFSET(::BackupPreference, _impl_.value_),
    ~0u,
    0,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::BackupSourcePreferences, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::BackupSourcePreferences, _impl_.source_key_),
    PROTOBUF_FIELD_OFFSET(::BackupSourcePreferences, _impl_.prefs_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::PreferenceValue, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::PreferenceValue, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::PreferenceValue, _impl_.value_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::IntPreferenceValue, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::IntPreferenceValue, _impl_.value_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::LongPreferenceValue, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::LongPreferenceValue, _impl_.value_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::FloatPreferenceValue, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::FloatPreferenceValue, _impl_.value_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::StringPreferenceValue, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::StringPreferenceValue, _impl_.value_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::BooleanPreferenceValue, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::BooleanPreferenceValue, _impl_.value_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::StringSetPreferenceValue, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::StringSetPreferenceValue, _impl_.value_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::BackupPreference)},
        {12, -1, -1, sizeof(::BackupSourcePreferences)},
        {22, -1, -1, sizeof(::PreferenceValue)},
        {37, -1, -1, sizeof(::IntPreferenceValue)},
        {46, -1, -1, sizeof(::LongPreferenceValue)},
        {55, -1, -1, sizeof(::FloatPreferenceValue)},
        {64, -1, -1, sizeof(::StringPreferenceValue)},
        {73, -1, -1, sizeof(::BooleanPreferenceValue)},
        {82, -1, -1, sizeof(::StringSetPreferenceValue)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_BackupPreference_default_instance_._instance,
    &::_BackupSourcePreferences_default_instance_._instance,
    &::_PreferenceValue_default_instance_._instance,
    &::_IntPreferenceValue_default_instance_._instance,
    &::_LongPreferenceValue_default_instance_._instance,
    &::_FloatPreferenceValue_default_instance_._instance,
    &::_StringPreferenceValue_default_instance_._instance,
    &::_BooleanPreferenceValue_default_instance_._instance,
    &::_StringSetPreferenceValue_default_instance_._instance,
};
const char descriptor_table_protodef_backup_5fpreference_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\027backup_preference.proto\"@\n\020BackupPrefe"
    "rence\022\013\n\003key\030\001 \001(\t\022\037\n\005value\030\002 \001(\0132\020.Pref"
    "erenceValue\"O\n\027BackupSourcePreferences\022\022"
    "\n\nsource_key\030\001 \001(\t\022 \n\005prefs\030\002 \003(\0132\021.Back"
    "upPreference\"\267\002\n\017PreferenceValue\022(\n\tint_"
    "value\030\001 \001(\0132\023.IntPreferenceValueH\000\022*\n\nlo"
    "ng_value\030\002 \001(\0132\024.LongPreferenceValueH\000\022,"
    "\n\013float_value\030\003 \001(\0132\025.FloatPreferenceVal"
    "ueH\000\022.\n\014string_value\030\004 \001(\0132\026.StringPrefe"
    "renceValueH\000\0220\n\rboolean_value\030\005 \001(\0132\027.Bo"
    "oleanPreferenceValueH\000\0225\n\020string_set_val"
    "ue\030\006 \001(\0132\031.StringSetPreferenceValueH\000B\007\n"
    "\005value\"#\n\022IntPreferenceValue\022\r\n\005value\030\001 "
    "\001(\005\"$\n\023LongPreferenceValue\022\r\n\005value\030\001 \001("
    "\003\"%\n\024FloatPreferenceValue\022\r\n\005value\030\001 \001(\002"
    "\"&\n\025StringPreferenceValue\022\r\n\005value\030\001 \001(\t"
    "\"\'\n\026BooleanPreferenceValue\022\r\n\005value\030\001 \001("
    "\010\")\n\030StringSetPreferenceValue\022\r\n\005value\030\001"
    " \003(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_backup_5fpreference_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_backup_5fpreference_2eproto = {
    false,
    false,
    732,
    descriptor_table_protodef_backup_5fpreference_2eproto,
    "backup_preference.proto",
    &descriptor_table_backup_5fpreference_2eproto_once,
    nullptr,
    0,
    9,
    schemas,
    file_default_instances,
    TableStruct_backup_5fpreference_2eproto::offsets,
    file_level_metadata_backup_5fpreference_2eproto,
    file_level_enum_descriptors_backup_5fpreference_2eproto,
    file_level_service_descriptors_backup_5fpreference_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_backup_5fpreference_2eproto_getter() {
  return &descriptor_table_backup_5fpreference_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_backup_5fpreference_2eproto(&descriptor_table_backup_5fpreference_2eproto);
// ===================================================================

class BackupPreference::_Internal {
 public:
  using HasBits = decltype(std::declval<BackupPreference>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(BackupPreference, _impl_._has_bits_);
  static const ::PreferenceValue& value(const BackupPreference* msg);
  static void set_has_value(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::PreferenceValue& BackupPreference::_Internal::value(const BackupPreference* msg) {
  return *msg->_impl_.value_;
}
BackupPreference::BackupPreference(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:BackupPreference)
}
inline PROTOBUF_NDEBUG_INLINE BackupPreference::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        key_(arena, from.key_) {}

BackupPreference::BackupPreference(
    ::google::protobuf::Arena* arena,
    const BackupPreference& from)
    : ::google::protobuf::Message(arena) {
  BackupPreference* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.value_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::PreferenceValue>(arena, *from._impl_.value_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:BackupPreference)
}
inline PROTOBUF_NDEBUG_INLINE BackupPreference::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        key_(arena) {}

inline void BackupPreference::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
BackupPreference::~BackupPreference() {
  // @@protoc_insertion_point(destructor:BackupPreference)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void BackupPreference::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.key_.Destroy();
  delete _impl_.value_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void BackupPreference::Clear() {
// @@protoc_insertion_point(message_clear_start:BackupPreference)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.key_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.value_ != nullptr);
    _impl_.value_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* BackupPreference::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 28, 2> BackupPreference::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BackupPreference, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_BackupPreference_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .PreferenceValue value = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(BackupPreference, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(BackupPreference, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(BackupPreference, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .PreferenceValue value = 2;
    {PROTOBUF_FIELD_OFFSET(BackupPreference, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::PreferenceValue>()},
  }}, {{
    "\20\3\0\0\0\0\0\0"
    "BackupPreference"
    "key"
  }},
};

::uint8_t* BackupPreference::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BackupPreference)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    const std::string& _s = this->_internal_key();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "BackupPreference.key");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .PreferenceValue value = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, _Internal::value(this),
        _Internal::value(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BackupPreference)
  return target;
}

::size_t BackupPreference::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BackupPreference)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_key());
  }

  // .PreferenceValue value = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.value_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData BackupPreference::_class_data_ = {
    BackupPreference::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* BackupPreference::GetClassData() const {
  return &_class_data_;
}

void BackupPreference::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<BackupPreference*>(&to_msg);
  auto& from = static_cast<const BackupPreference&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BackupPreference)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_value()->::PreferenceValue::MergeFrom(
        from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BackupPreference::CopyFrom(const BackupPreference& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BackupPreference)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool BackupPreference::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* BackupPreference::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void BackupPreference::InternalSwap(BackupPreference* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
  swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata BackupPreference::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_backup_5fpreference_2eproto_getter, &descriptor_table_backup_5fpreference_2eproto_once,
      file_level_metadata_backup_5fpreference_2eproto[0]);
}
// ===================================================================

class BackupSourcePreferences::_Internal {
 public:
};

BackupSourcePreferences::BackupSourcePreferences(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:BackupSourcePreferences)
}
inline PROTOBUF_NDEBUG_INLINE BackupSourcePreferences::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : prefs_{visibility, arena, from.prefs_},
        source_key_(arena, from.source_key_),
        _cached_size_{0} {}

BackupSourcePreferences::BackupSourcePreferences(
    ::google::protobuf::Arena* arena,
    const BackupSourcePreferences& from)
    : ::google::protobuf::Message(arena) {
  BackupSourcePreferences* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:BackupSourcePreferences)
}
inline PROTOBUF_NDEBUG_INLINE BackupSourcePreferences::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : prefs_{visibility, arena},
        source_key_(arena),
        _cached_size_{0} {}

inline void BackupSourcePreferences::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
BackupSourcePreferences::~BackupSourcePreferences() {
  // @@protoc_insertion_point(destructor:BackupSourcePreferences)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void BackupSourcePreferences::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.source_key_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void BackupSourcePreferences::Clear() {
// @@protoc_insertion_point(message_clear_start:BackupSourcePreferences)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.prefs_.Clear();
  _impl_.source_key_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* BackupSourcePreferences::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 42, 2> BackupSourcePreferences::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_BackupSourcePreferences_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .BackupPreference prefs = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(BackupSourcePreferences, _impl_.prefs_)}},
    // string source_key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(BackupSourcePreferences, _impl_.source_key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string source_key = 1;
    {PROTOBUF_FIELD_OFFSET(BackupSourcePreferences, _impl_.source_key_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .BackupPreference prefs = 2;
    {PROTOBUF_FIELD_OFFSET(BackupSourcePreferences, _impl_.prefs_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::BackupPreference>()},
  }}, {{
    "\27\12\0\0\0\0\0\0"
    "BackupSourcePreferences"
    "source_key"
  }},
};

::uint8_t* BackupSourcePreferences::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BackupSourcePreferences)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string source_key = 1;
  if (!this->_internal_source_key().empty()) {
    const std::string& _s = this->_internal_source_key();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "BackupSourcePreferences.source_key");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // repeated .BackupPreference prefs = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_prefs_size()); i < n; i++) {
    const auto& repfield = this->_internal_prefs().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BackupSourcePreferences)
  return target;
}

::size_t BackupSourcePreferences::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BackupSourcePreferences)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .BackupPreference prefs = 2;
  total_size += 1UL * this->_internal_prefs_size();
  for (const auto& msg : this->_internal_prefs()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string source_key = 1;
  if (!this->_internal_source_key().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_source_key());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData BackupSourcePreferences::_class_data_ = {
    BackupSourcePreferences::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* BackupSourcePreferences::GetClassData() const {
  return &_class_data_;
}

void BackupSourcePreferences::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<BackupSourcePreferences*>(&to_msg);
  auto& from = static_cast<const BackupSourcePreferences&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BackupSourcePreferences)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_prefs()->MergeFrom(
      from._internal_prefs());
  if (!from._internal_source_key().empty()) {
    _this->_internal_set_source_key(from._internal_source_key());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BackupSourcePreferences::CopyFrom(const BackupSourcePreferences& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BackupSourcePreferences)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool BackupSourcePreferences::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* BackupSourcePreferences::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void BackupSourcePreferences::InternalSwap(BackupSourcePreferences* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.prefs_.InternalSwap(&other->_impl_.prefs_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.source_key_, &other->_impl_.source_key_, arena);
}

::google::protobuf::Metadata BackupSourcePreferences::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_backup_5fpreference_2eproto_getter, &descriptor_table_backup_5fpreference_2eproto_once,
      file_level_metadata_backup_5fpreference_2eproto[1]);
}
// ===================================================================

class PreferenceValue::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::PreferenceValue, _impl_._oneof_case_);
  static const ::IntPreferenceValue& int_value(const PreferenceValue* msg);
  static const ::LongPreferenceValue& long_value(const PreferenceValue* msg);
  static const ::FloatPreferenceValue& float_value(const PreferenceValue* msg);
  static const ::StringPreferenceValue& string_value(const PreferenceValue* msg);
  static const ::BooleanPreferenceValue& boolean_value(const PreferenceValue* msg);
  static const ::StringSetPreferenceValue& string_set_value(const PreferenceValue* msg);
};

const ::IntPreferenceValue& PreferenceValue::_Internal::int_value(const PreferenceValue* msg) {
  return *msg->_impl_.value_.int_value_;
}
const ::LongPreferenceValue& PreferenceValue::_Internal::long_value(const PreferenceValue* msg) {
  return *msg->_impl_.value_.long_value_;
}
const ::FloatPreferenceValue& PreferenceValue::_Internal::float_value(const PreferenceValue* msg) {
  return *msg->_impl_.value_.float_value_;
}
const ::StringPreferenceValue& PreferenceValue::_Internal::string_value(const PreferenceValue* msg) {
  return *msg->_impl_.value_.string_value_;
}
const ::BooleanPreferenceValue& PreferenceValue::_Internal::boolean_value(const PreferenceValue* msg) {
  return *msg->_impl_.value_.boolean_value_;
}
const ::StringSetPreferenceValue& PreferenceValue::_Internal::string_set_value(const PreferenceValue* msg) {
  return *msg->_impl_.value_.string_set_value_;
}
void PreferenceValue::set_allocated_int_value(::IntPreferenceValue* int_value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_value();
  if (int_value) {
    ::google::protobuf::Arena* submessage_arena = int_value->GetArena();
    if (message_arena != submessage_arena) {
      int_value = ::google::protobuf::internal::GetOwnedMessage(message_arena, int_value, submessage_arena);
    }
    set_has_int_value();
    _impl_.value_.int_value_ = int_value;
  }
  // @@protoc_insertion_point(field_set_allocated:PreferenceValue.int_value)
}
void PreferenceValue::set_allocated_long_value(::LongPreferenceValue* long_value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_value();
  if (long_value) {
    ::google::protobuf::Arena* submessage_arena = long_value->GetArena();
    if (message_arena != submessage_arena) {
      long_value = ::google::protobuf::internal::GetOwnedMessage(message_arena, long_value, submessage_arena);
    }
    set_has_long_value();
    _impl_.value_.long_value_ = long_value;
  }
  // @@protoc_insertion_point(field_set_allocated:PreferenceValue.long_value)
}
void PreferenceValue::set_allocated_float_value(::FloatPreferenceValue* float_value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_value();
  if (float_value) {
    ::google::protobuf::Arena* submessage_arena = float_value->GetArena();
    if (message_arena != submessage_arena) {
      float_value = ::google::protobuf::internal::GetOwnedMessage(message_arena, float_value, submessage_arena);
    }
    set_has_float_value();
    _impl_.value_.float_value_ = float_value;
  }
  // @@protoc_insertion_point(field_set_allocated:PreferenceValue.float_value)
}
void PreferenceValue::set_allocated_string_value(::StringPreferenceValue* string_value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_value();
  if (string_value) {
    ::google::protobuf::Arena* submessage_arena = string_value->GetArena();
    if (message_arena != submessage_arena) {
      string_value = ::google::protobuf::internal::GetOwnedMessage(message_arena, string_value, submessage_arena);
    }
    set_has_string_value();
    _impl_.value_.string_value_ = string_value;
  }
  // @@protoc_insertion_point(field_set_allocated:PreferenceValue.string_value)
}
void PreferenceValue::set_allocated_boolean_value(::BooleanPreferenceValue* boolean_value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_value();
  if (boolean_value) {
    ::google::protobuf::Arena* submessage_arena = boolean_value->GetArena();
    if (message_arena != submessage_arena) {
      boolean_value = ::google::protobuf::internal::GetOwnedMessage(message_arena, boolean_value, submessage_arena);
    }
    set_has_boolean_value();
    _impl_.value_.boolean_value_ = boolean_value;
  }
  // @@protoc_insertion_point(field_set_allocated:PreferenceValue.boolean_value)
}
void PreferenceValue::set_allocated_string_set_value(::StringSetPreferenceValue* string_set_value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_value();
  if (string_set_value) {
    ::google::protobuf::Arena* submessage_arena = string_set_value->GetArena();
    if (message_arena != submessage_arena) {
      string_set_value = ::google::protobuf::internal::GetOwnedMessage(message_arena, string_set_value, submessage_arena);
    }
    set_has_string_set_value();
    _impl_.value_.string_set_value_ = string_set_value;
  }
  // @@protoc_insertion_point(field_set_allocated:PreferenceValue.string_set_value)
}
PreferenceValue::PreferenceValue(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PreferenceValue)
}
inline PROTOBUF_NDEBUG_INLINE PreferenceValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : value_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

PreferenceValue::PreferenceValue(
    ::google::protobuf::Arena* arena,
    const PreferenceValue& from)
    : ::google::protobuf::Message(arena) {
  PreferenceValue* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  switch (value_case()) {
    case VALUE_NOT_SET:
      break;
      case kIntValue:
        _impl_.value_.int_value_ = CreateMaybeMessage<::IntPreferenceValue>(arena, *from._impl_.value_.int_value_);
        break;
      case kLongValue:
        _impl_.value_.long_value_ = CreateMaybeMessage<::LongPreferenceValue>(arena, *from._impl_.value_.long_value_);
        break;
      case kFloatValue:
        _impl_.value_.float_value_ = CreateMaybeMessage<::FloatPreferenceValue>(arena, *from._impl_.value_.float_value_);
        break;
      case kStringValue:
        _impl_.value_.string_value_ = CreateMaybeMessage<::StringPreferenceValue>(arena, *from._impl_.value_.string_value_);
        break;
      case kBooleanValue:
        _impl_.value_.boolean_value_ = CreateMaybeMessage<::BooleanPreferenceValue>(arena, *from._impl_.value_.boolean_value_);
        break;
      case kStringSetValue:
        _impl_.value_.string_set_value_ = CreateMaybeMessage<::StringSetPreferenceValue>(arena, *from._impl_.value_.string_set_value_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:PreferenceValue)
}
inline PROTOBUF_NDEBUG_INLINE PreferenceValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : value_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void PreferenceValue::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PreferenceValue::~PreferenceValue() {
  // @@protoc_insertion_point(destructor:PreferenceValue)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PreferenceValue::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_value()) {
    clear_value();
  }
  _impl_.~Impl_();
}

void PreferenceValue::clear_value() {
// @@protoc_insertion_point(one_of_clear_start:PreferenceValue)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (value_case()) {
    case kIntValue: {
      if (GetArena() == nullptr) {
        delete _impl_.value_.int_value_;
      }
      break;
    }
    case kLongValue: {
      if (GetArena() == nullptr) {
        delete _impl_.value_.long_value_;
      }
      break;
    }
    case kFloatValue: {
      if (GetArena() == nullptr) {
        delete _impl_.value_.float_value_;
      }
      break;
    }
    case kStringValue: {
      if (GetArena() == nullptr) {
        delete _impl_.value_.string_value_;
      }
      break;
    }
    case kBooleanValue: {
      if (GetArena() == nullptr) {
        delete _impl_.value_.boolean_value_;
      }
      break;
    }
    case kStringSetValue: {
      if (GetArena() == nullptr) {
        delete _impl_.value_.string_set_value_;
      }
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = VALUE_NOT_SET;
}


PROTOBUF_NOINLINE void PreferenceValue::Clear() {
// @@protoc_insertion_point(message_clear_start:PreferenceValue)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_value();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PreferenceValue::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 6, 6, 0, 2> PreferenceValue::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    6,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_PreferenceValue_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .IntPreferenceValue int_value = 1;
    {PROTOBUF_FIELD_OFFSET(PreferenceValue, _impl_.value_.int_value_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .LongPreferenceValue long_value = 2;
    {PROTOBUF_FIELD_OFFSET(PreferenceValue, _impl_.value_.long_value_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .FloatPreferenceValue float_value = 3;
    {PROTOBUF_FIELD_OFFSET(PreferenceValue, _impl_.value_.float_value_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .StringPreferenceValue string_value = 4;
    {PROTOBUF_FIELD_OFFSET(PreferenceValue, _impl_.value_.string_value_), _Internal::kOneofCaseOffset + 0, 3,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .BooleanPreferenceValue boolean_value = 5;
    {PROTOBUF_FIELD_OFFSET(PreferenceValue, _impl_.value_.boolean_value_), _Internal::kOneofCaseOffset + 0, 4,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .StringSetPreferenceValue string_set_value = 6;
    {PROTOBUF_FIELD_OFFSET(PreferenceValue, _impl_.value_.string_set_value_), _Internal::kOneofCaseOffset + 0, 5,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::IntPreferenceValue>()},
    {::_pbi::TcParser::GetTable<::LongPreferenceValue>()},
    {::_pbi::TcParser::GetTable<::FloatPreferenceValue>()},
    {::_pbi::TcParser::GetTable<::StringPreferenceValue>()},
    {::_pbi::TcParser::GetTable<::BooleanPreferenceValue>()},
    {::_pbi::TcParser::GetTable<::StringSetPreferenceValue>()},
  }}, {{
  }},
};

::uint8_t* PreferenceValue::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PreferenceValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (value_case()) {
    case kIntValue: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, _Internal::int_value(this),
          _Internal::int_value(this).GetCachedSize(), target, stream);
      break;
    }
    case kLongValue: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, _Internal::long_value(this),
          _Internal::long_value(this).GetCachedSize(), target, stream);
      break;
    }
    case kFloatValue: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, _Internal::float_value(this),
          _Internal::float_value(this).GetCachedSize(), target, stream);
      break;
    }
    case kStringValue: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, _Internal::string_value(this),
          _Internal::string_value(this).GetCachedSize(), target, stream);
      break;
    }
    case kBooleanValue: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          5, _Internal::boolean_value(this),
          _Internal::boolean_value(this).GetCachedSize(), target, stream);
      break;
    }
    case kStringSetValue: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          6, _Internal::string_set_value(this),
          _Internal::string_set_value(this).GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PreferenceValue)
  return target;
}

::size_t PreferenceValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PreferenceValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (value_case()) {
    // .IntPreferenceValue int_value = 1;
    case kIntValue: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.value_.int_value_);
      break;
    }
    // .LongPreferenceValue long_value = 2;
    case kLongValue: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.value_.long_value_);
      break;
    }
    // .FloatPreferenceValue float_value = 3;
    case kFloatValue: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.value_.float_value_);
      break;
    }
    // .StringPreferenceValue string_value = 4;
    case kStringValue: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.value_.string_value_);
      break;
    }
    // .BooleanPreferenceValue boolean_value = 5;
    case kBooleanValue: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.value_.boolean_value_);
      break;
    }
    // .StringSetPreferenceValue string_set_value = 6;
    case kStringSetValue: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.value_.string_set_value_);
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PreferenceValue::_class_data_ = {
    PreferenceValue::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PreferenceValue::GetClassData() const {
  return &_class_data_;
}

void PreferenceValue::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PreferenceValue*>(&to_msg);
  auto& from = static_cast<const PreferenceValue&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PreferenceValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.value_case()) {
    case kIntValue: {
      _this->_internal_mutable_int_value()->::IntPreferenceValue::MergeFrom(
          from._internal_int_value());
      break;
    }
    case kLongValue: {
      _this->_internal_mutable_long_value()->::LongPreferenceValue::MergeFrom(
          from._internal_long_value());
      break;
    }
    case kFloatValue: {
      _this->_internal_mutable_float_value()->::FloatPreferenceValue::MergeFrom(
          from._internal_float_value());
      break;
    }
    case kStringValue: {
      _this->_internal_mutable_string_value()->::StringPreferenceValue::MergeFrom(
          from._internal_string_value());
      break;
    }
    case kBooleanValue: {
      _this->_internal_mutable_boolean_value()->::BooleanPreferenceValue::MergeFrom(
          from._internal_boolean_value());
      break;
    }
    case kStringSetValue: {
      _this->_internal_mutable_string_set_value()->::StringSetPreferenceValue::MergeFrom(
          from._internal_string_set_value());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PreferenceValue::CopyFrom(const PreferenceValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PreferenceValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PreferenceValue::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PreferenceValue::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PreferenceValue::InternalSwap(PreferenceValue* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.value_, other->_impl_.value_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata PreferenceValue::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_backup_5fpreference_2eproto_getter, &descriptor_table_backup_5fpreference_2eproto_once,
      file_level_metadata_backup_5fpreference_2eproto[2]);
}
// ===================================================================

class IntPreferenceValue::_Internal {
 public:
};

IntPreferenceValue::IntPreferenceValue(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:IntPreferenceValue)
}
IntPreferenceValue::IntPreferenceValue(
    ::google::protobuf::Arena* arena, const IntPreferenceValue& from)
    : IntPreferenceValue(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE IntPreferenceValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void IntPreferenceValue::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
IntPreferenceValue::~IntPreferenceValue() {
  // @@protoc_insertion_point(destructor:IntPreferenceValue)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void IntPreferenceValue::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void IntPreferenceValue::Clear() {
// @@protoc_insertion_point(message_clear_start:IntPreferenceValue)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* IntPreferenceValue::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> IntPreferenceValue::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_IntPreferenceValue_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 value = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(IntPreferenceValue, _impl_.value_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(IntPreferenceValue, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 value = 1;
    {PROTOBUF_FIELD_OFFSET(IntPreferenceValue, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* IntPreferenceValue::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:IntPreferenceValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 value = 1;
  if (this->_internal_value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:IntPreferenceValue)
  return target;
}

::size_t IntPreferenceValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:IntPreferenceValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 value = 1;
  if (this->_internal_value() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData IntPreferenceValue::_class_data_ = {
    IntPreferenceValue::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* IntPreferenceValue::GetClassData() const {
  return &_class_data_;
}

void IntPreferenceValue::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<IntPreferenceValue*>(&to_msg);
  auto& from = static_cast<const IntPreferenceValue&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:IntPreferenceValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_value() != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void IntPreferenceValue::CopyFrom(const IntPreferenceValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IntPreferenceValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool IntPreferenceValue::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* IntPreferenceValue::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void IntPreferenceValue::InternalSwap(IntPreferenceValue* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata IntPreferenceValue::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_backup_5fpreference_2eproto_getter, &descriptor_table_backup_5fpreference_2eproto_once,
      file_level_metadata_backup_5fpreference_2eproto[3]);
}
// ===================================================================

class LongPreferenceValue::_Internal {
 public:
};

LongPreferenceValue::LongPreferenceValue(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:LongPreferenceValue)
}
LongPreferenceValue::LongPreferenceValue(
    ::google::protobuf::Arena* arena, const LongPreferenceValue& from)
    : LongPreferenceValue(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE LongPreferenceValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void LongPreferenceValue::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
LongPreferenceValue::~LongPreferenceValue() {
  // @@protoc_insertion_point(destructor:LongPreferenceValue)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LongPreferenceValue::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void LongPreferenceValue::Clear() {
// @@protoc_insertion_point(message_clear_start:LongPreferenceValue)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LongPreferenceValue::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> LongPreferenceValue::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LongPreferenceValue_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int64 value = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LongPreferenceValue, _impl_.value_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LongPreferenceValue, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 value = 1;
    {PROTOBUF_FIELD_OFFSET(LongPreferenceValue, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* LongPreferenceValue::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:LongPreferenceValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 value = 1;
  if (this->_internal_value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LongPreferenceValue)
  return target;
}

::size_t LongPreferenceValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LongPreferenceValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 value = 1;
  if (this->_internal_value() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData LongPreferenceValue::_class_data_ = {
    LongPreferenceValue::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* LongPreferenceValue::GetClassData() const {
  return &_class_data_;
}

void LongPreferenceValue::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<LongPreferenceValue*>(&to_msg);
  auto& from = static_cast<const LongPreferenceValue&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LongPreferenceValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_value() != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LongPreferenceValue::CopyFrom(const LongPreferenceValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LongPreferenceValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LongPreferenceValue::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* LongPreferenceValue::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void LongPreferenceValue::InternalSwap(LongPreferenceValue* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata LongPreferenceValue::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_backup_5fpreference_2eproto_getter, &descriptor_table_backup_5fpreference_2eproto_once,
      file_level_metadata_backup_5fpreference_2eproto[4]);
}
// ===================================================================

class FloatPreferenceValue::_Internal {
 public:
};

FloatPreferenceValue::FloatPreferenceValue(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FloatPreferenceValue)
}
FloatPreferenceValue::FloatPreferenceValue(
    ::google::protobuf::Arena* arena, const FloatPreferenceValue& from)
    : FloatPreferenceValue(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE FloatPreferenceValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void FloatPreferenceValue::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
FloatPreferenceValue::~FloatPreferenceValue() {
  // @@protoc_insertion_point(destructor:FloatPreferenceValue)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FloatPreferenceValue::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FloatPreferenceValue::Clear() {
// @@protoc_insertion_point(message_clear_start:FloatPreferenceValue)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FloatPreferenceValue::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> FloatPreferenceValue::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FloatPreferenceValue_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // float value = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(FloatPreferenceValue, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float value = 1;
    {PROTOBUF_FIELD_OFFSET(FloatPreferenceValue, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* FloatPreferenceValue::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:FloatPreferenceValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // float value = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_value = this->_internal_value();
  ::uint32_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FloatPreferenceValue)
  return target;
}

::size_t FloatPreferenceValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FloatPreferenceValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float value = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_value = this->_internal_value();
  ::uint32_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FloatPreferenceValue::_class_data_ = {
    FloatPreferenceValue::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FloatPreferenceValue::GetClassData() const {
  return &_class_data_;
}

void FloatPreferenceValue::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FloatPreferenceValue*>(&to_msg);
  auto& from = static_cast<const FloatPreferenceValue&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:FloatPreferenceValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_value = from._internal_value();
  ::uint32_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FloatPreferenceValue::CopyFrom(const FloatPreferenceValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FloatPreferenceValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FloatPreferenceValue::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FloatPreferenceValue::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FloatPreferenceValue::InternalSwap(FloatPreferenceValue* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata FloatPreferenceValue::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_backup_5fpreference_2eproto_getter, &descriptor_table_backup_5fpreference_2eproto_once,
      file_level_metadata_backup_5fpreference_2eproto[5]);
}
// ===================================================================

class StringPreferenceValue::_Internal {
 public:
};

StringPreferenceValue::StringPreferenceValue(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:StringPreferenceValue)
}
inline PROTOBUF_NDEBUG_INLINE StringPreferenceValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : value_(arena, from.value_),
        _cached_size_{0} {}

StringPreferenceValue::StringPreferenceValue(
    ::google::protobuf::Arena* arena,
    const StringPreferenceValue& from)
    : ::google::protobuf::Message(arena) {
  StringPreferenceValue* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:StringPreferenceValue)
}
inline PROTOBUF_NDEBUG_INLINE StringPreferenceValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : value_(arena),
        _cached_size_{0} {}

inline void StringPreferenceValue::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
StringPreferenceValue::~StringPreferenceValue() {
  // @@protoc_insertion_point(destructor:StringPreferenceValue)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void StringPreferenceValue::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.value_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void StringPreferenceValue::Clear() {
// @@protoc_insertion_point(message_clear_start:StringPreferenceValue)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* StringPreferenceValue::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 35, 2> StringPreferenceValue::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_StringPreferenceValue_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string value = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(StringPreferenceValue, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string value = 1;
    {PROTOBUF_FIELD_OFFSET(StringPreferenceValue, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\5\0\0\0\0\0\0"
    "StringPreferenceValue"
    "value"
  }},
};

::uint8_t* StringPreferenceValue::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:StringPreferenceValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string value = 1;
  if (!this->_internal_value().empty()) {
    const std::string& _s = this->_internal_value();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "StringPreferenceValue.value");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:StringPreferenceValue)
  return target;
}

::size_t StringPreferenceValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:StringPreferenceValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string value = 1;
  if (!this->_internal_value().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData StringPreferenceValue::_class_data_ = {
    StringPreferenceValue::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* StringPreferenceValue::GetClassData() const {
  return &_class_data_;
}

void StringPreferenceValue::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<StringPreferenceValue*>(&to_msg);
  auto& from = static_cast<const StringPreferenceValue&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:StringPreferenceValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StringPreferenceValue::CopyFrom(const StringPreferenceValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:StringPreferenceValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool StringPreferenceValue::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* StringPreferenceValue::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void StringPreferenceValue::InternalSwap(StringPreferenceValue* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
}

::google::protobuf::Metadata StringPreferenceValue::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_backup_5fpreference_2eproto_getter, &descriptor_table_backup_5fpreference_2eproto_once,
      file_level_metadata_backup_5fpreference_2eproto[6]);
}
// ===================================================================

class BooleanPreferenceValue::_Internal {
 public:
};

BooleanPreferenceValue::BooleanPreferenceValue(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:BooleanPreferenceValue)
}
BooleanPreferenceValue::BooleanPreferenceValue(
    ::google::protobuf::Arena* arena, const BooleanPreferenceValue& from)
    : BooleanPreferenceValue(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE BooleanPreferenceValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void BooleanPreferenceValue::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
BooleanPreferenceValue::~BooleanPreferenceValue() {
  // @@protoc_insertion_point(destructor:BooleanPreferenceValue)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void BooleanPreferenceValue::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void BooleanPreferenceValue::Clear() {
// @@protoc_insertion_point(message_clear_start:BooleanPreferenceValue)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* BooleanPreferenceValue::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> BooleanPreferenceValue::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_BooleanPreferenceValue_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool value = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(BooleanPreferenceValue, _impl_.value_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(BooleanPreferenceValue, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool value = 1;
    {PROTOBUF_FIELD_OFFSET(BooleanPreferenceValue, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* BooleanPreferenceValue::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BooleanPreferenceValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool value = 1;
  if (this->_internal_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BooleanPreferenceValue)
  return target;
}

::size_t BooleanPreferenceValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BooleanPreferenceValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool value = 1;
  if (this->_internal_value() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData BooleanPreferenceValue::_class_data_ = {
    BooleanPreferenceValue::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* BooleanPreferenceValue::GetClassData() const {
  return &_class_data_;
}

void BooleanPreferenceValue::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<BooleanPreferenceValue*>(&to_msg);
  auto& from = static_cast<const BooleanPreferenceValue&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BooleanPreferenceValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_value() != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BooleanPreferenceValue::CopyFrom(const BooleanPreferenceValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BooleanPreferenceValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool BooleanPreferenceValue::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* BooleanPreferenceValue::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void BooleanPreferenceValue::InternalSwap(BooleanPreferenceValue* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata BooleanPreferenceValue::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_backup_5fpreference_2eproto_getter, &descriptor_table_backup_5fpreference_2eproto_once,
      file_level_metadata_backup_5fpreference_2eproto[7]);
}
// ===================================================================

class StringSetPreferenceValue::_Internal {
 public:
};

StringSetPreferenceValue::StringSetPreferenceValue(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:StringSetPreferenceValue)
}
inline PROTOBUF_NDEBUG_INLINE StringSetPreferenceValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : value_{visibility, arena, from.value_},
        _cached_size_{0} {}

StringSetPreferenceValue::StringSetPreferenceValue(
    ::google::protobuf::Arena* arena,
    const StringSetPreferenceValue& from)
    : ::google::protobuf::Message(arena) {
  StringSetPreferenceValue* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:StringSetPreferenceValue)
}
inline PROTOBUF_NDEBUG_INLINE StringSetPreferenceValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : value_{visibility, arena},
        _cached_size_{0} {}

inline void StringSetPreferenceValue::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
StringSetPreferenceValue::~StringSetPreferenceValue() {
  // @@protoc_insertion_point(destructor:StringSetPreferenceValue)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void StringSetPreferenceValue::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void StringSetPreferenceValue::Clear() {
// @@protoc_insertion_point(message_clear_start:StringSetPreferenceValue)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* StringSetPreferenceValue::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 38, 2> StringSetPreferenceValue::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_StringSetPreferenceValue_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated string value = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(StringSetPreferenceValue, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string value = 1;
    {PROTOBUF_FIELD_OFFSET(StringSetPreferenceValue, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\30\5\0\0\0\0\0\0"
    "StringSetPreferenceValue"
    "value"
  }},
};

::uint8_t* StringSetPreferenceValue::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:StringSetPreferenceValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated string value = 1;
  for (int i = 0, n = this->_internal_value_size(); i < n; ++i) {
    const auto& s = this->_internal_value().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "StringSetPreferenceValue.value");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:StringSetPreferenceValue)
  return target;
}

::size_t StringSetPreferenceValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:StringSetPreferenceValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string value = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_value().size());
  for (int i = 0, n = _internal_value().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_value().Get(i));
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData StringSetPreferenceValue::_class_data_ = {
    StringSetPreferenceValue::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* StringSetPreferenceValue::GetClassData() const {
  return &_class_data_;
}

void StringSetPreferenceValue::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<StringSetPreferenceValue*>(&to_msg);
  auto& from = static_cast<const StringSetPreferenceValue&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:StringSetPreferenceValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_value()->MergeFrom(from._internal_value());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StringSetPreferenceValue::CopyFrom(const StringSetPreferenceValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:StringSetPreferenceValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool StringSetPreferenceValue::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* StringSetPreferenceValue::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void StringSetPreferenceValue::InternalSwap(StringSetPreferenceValue* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.value_.InternalSwap(&other->_impl_.value_);
}

::google::protobuf::Metadata StringSetPreferenceValue::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_backup_5fpreference_2eproto_getter, &descriptor_table_backup_5fpreference_2eproto_once,
      file_level_metadata_backup_5fpreference_2eproto[8]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
