// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tachiyomi.proto

#include "tachiyomi.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Backup::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : mangabackup_{},
        categories_{},
        brokensources_{},
        sources_{},
        preferences_{},
        sourcepreferences_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Backup::Backup(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct BackupDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BackupDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BackupDefaultTypeInternal() {}
  union {
    Backup _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BackupDefaultTypeInternal _Backup_default_instance_;
static ::_pb::Metadata file_level_metadata_tachiyomi_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_tachiyomi_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_tachiyomi_2eproto = nullptr;
const ::uint32_t TableStruct_tachiyomi_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Backup, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Backup, _impl_.mangabackup_),
    PROTOBUF_FIELD_OFFSET(::Backup, _impl_.categories_),
    PROTOBUF_FIELD_OFFSET(::Backup, _impl_.brokensources_),
    PROTOBUF_FIELD_OFFSET(::Backup, _impl_.sources_),
    PROTOBUF_FIELD_OFFSET(::Backup, _impl_.preferences_),
    PROTOBUF_FIELD_OFFSET(::Backup, _impl_.sourcepreferences_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Backup)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_Backup_default_instance_._instance,
};
const char descriptor_table_protodef_tachiyomi_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\017tachiyomi.proto\032\025backup_category.proto"
    "\032\022backup_manga.proto\032\027backup_preference."
    "proto\032\023backup_source.proto\"\371\001\n\006Backup\022!\n"
    "\013mangaBackup\030\001 \003(\0132\014.BackupManga\022#\n\ncate"
    "gories\030\002 \003(\0132\017.BackupCategory\022*\n\rbrokenS"
    "ources\030d \003(\0132\023.BrokenBackupSource\022\036\n\007sou"
    "rces\030e \003(\0132\r.BackupSource\022&\n\013preferences"
    "\030h \003(\0132\021.BackupPreference\0223\n\021sourcePrefe"
    "rences\030i \003(\0132\030.BackupSourcePreferencesb\006"
    "proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_tachiyomi_2eproto_deps[4] =
    {
        &::descriptor_table_backup_5fcategory_2eproto,
        &::descriptor_table_backup_5fmanga_2eproto,
        &::descriptor_table_backup_5fpreference_2eproto,
        &::descriptor_table_backup_5fsource_2eproto,
};
static ::absl::once_flag descriptor_table_tachiyomi_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_tachiyomi_2eproto = {
    false,
    false,
    366,
    descriptor_table_protodef_tachiyomi_2eproto,
    "tachiyomi.proto",
    &descriptor_table_tachiyomi_2eproto_once,
    descriptor_table_tachiyomi_2eproto_deps,
    4,
    1,
    schemas,
    file_default_instances,
    TableStruct_tachiyomi_2eproto::offsets,
    file_level_metadata_tachiyomi_2eproto,
    file_level_enum_descriptors_tachiyomi_2eproto,
    file_level_service_descriptors_tachiyomi_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_tachiyomi_2eproto_getter() {
  return &descriptor_table_tachiyomi_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_tachiyomi_2eproto(&descriptor_table_tachiyomi_2eproto);
// ===================================================================

class Backup::_Internal {
 public:
};

void Backup::clear_mangabackup() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.mangabackup_.Clear();
}
void Backup::clear_categories() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.categories_.Clear();
}
void Backup::clear_brokensources() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.brokensources_.Clear();
}
void Backup::clear_sources() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.sources_.Clear();
}
void Backup::clear_preferences() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.preferences_.Clear();
}
void Backup::clear_sourcepreferences() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.sourcepreferences_.Clear();
}
Backup::Backup(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Backup)
}
inline PROTOBUF_NDEBUG_INLINE Backup::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : mangabackup_{visibility, arena, from.mangabackup_},
        categories_{visibility, arena, from.categories_},
        brokensources_{visibility, arena, from.brokensources_},
        sources_{visibility, arena, from.sources_},
        preferences_{visibility, arena, from.preferences_},
        sourcepreferences_{visibility, arena, from.sourcepreferences_},
        _cached_size_{0} {}

Backup::Backup(
    ::google::protobuf::Arena* arena,
    const Backup& from)
    : ::google::protobuf::Message(arena) {
  Backup* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:Backup)
}
inline PROTOBUF_NDEBUG_INLINE Backup::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : mangabackup_{visibility, arena},
        categories_{visibility, arena},
        brokensources_{visibility, arena},
        sources_{visibility, arena},
        preferences_{visibility, arena},
        sourcepreferences_{visibility, arena},
        _cached_size_{0} {}

inline void Backup::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Backup::~Backup() {
  // @@protoc_insertion_point(destructor:Backup)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Backup::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Backup::Clear() {
// @@protoc_insertion_point(message_clear_start:Backup)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.mangabackup_.Clear();
  _impl_.categories_.Clear();
  _impl_.brokensources_.Clear();
  _impl_.sources_.Clear();
  _impl_.preferences_.Clear();
  _impl_.sourcepreferences_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Backup::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 6, 0, 7> Backup::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    105, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    6,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Backup_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .BackupPreference preferences = 104;
    {::_pbi::TcParser::FastMtR2,
     {1730, 63, 4, PROTOBUF_FIELD_OFFSET(Backup, _impl_.preferences_)}},
    // repeated .BackupManga mangaBackup = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Backup, _impl_.mangabackup_)}},
    // repeated .BackupCategory categories = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(Backup, _impl_.categories_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // repeated .BrokenBackupSource brokenSources = 100;
    {::_pbi::TcParser::FastMtR2,
     {1698, 63, 2, PROTOBUF_FIELD_OFFSET(Backup, _impl_.brokensources_)}},
    // repeated .BackupSource sources = 101;
    {::_pbi::TcParser::FastMtR2,
     {1706, 63, 3, PROTOBUF_FIELD_OFFSET(Backup, _impl_.sources_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    100, 0, 1,
    65484, 2,
    65535, 65535
  }}, {{
    // repeated .BackupManga mangaBackup = 1;
    {PROTOBUF_FIELD_OFFSET(Backup, _impl_.mangabackup_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .BackupCategory categories = 2;
    {PROTOBUF_FIELD_OFFSET(Backup, _impl_.categories_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .BrokenBackupSource brokenSources = 100;
    {PROTOBUF_FIELD_OFFSET(Backup, _impl_.brokensources_), 0, 2,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .BackupSource sources = 101;
    {PROTOBUF_FIELD_OFFSET(Backup, _impl_.sources_), 0, 3,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .BackupPreference preferences = 104;
    {PROTOBUF_FIELD_OFFSET(Backup, _impl_.preferences_), 0, 4,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .BackupSourcePreferences sourcePreferences = 105;
    {PROTOBUF_FIELD_OFFSET(Backup, _impl_.sourcepreferences_), 0, 5,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::BackupManga>()},
    {::_pbi::TcParser::GetTable<::BackupCategory>()},
    {::_pbi::TcParser::GetTable<::BrokenBackupSource>()},
    {::_pbi::TcParser::GetTable<::BackupSource>()},
    {::_pbi::TcParser::GetTable<::BackupPreference>()},
    {::_pbi::TcParser::GetTable<::BackupSourcePreferences>()},
  }}, {{
  }},
};

::uint8_t* Backup::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Backup)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .BackupManga mangaBackup = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_mangabackup_size()); i < n; i++) {
    const auto& repfield = this->_internal_mangabackup().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .BackupCategory categories = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_categories_size()); i < n; i++) {
    const auto& repfield = this->_internal_categories().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .BrokenBackupSource brokenSources = 100;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_brokensources_size()); i < n; i++) {
    const auto& repfield = this->_internal_brokensources().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(100, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .BackupSource sources = 101;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_sources_size()); i < n; i++) {
    const auto& repfield = this->_internal_sources().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(101, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .BackupPreference preferences = 104;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_preferences_size()); i < n; i++) {
    const auto& repfield = this->_internal_preferences().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(104, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .BackupSourcePreferences sourcePreferences = 105;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_sourcepreferences_size()); i < n; i++) {
    const auto& repfield = this->_internal_sourcepreferences().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(105, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Backup)
  return target;
}

::size_t Backup::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Backup)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .BackupManga mangaBackup = 1;
  total_size += 1UL * this->_internal_mangabackup_size();
  for (const auto& msg : this->_internal_mangabackup()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // repeated .BackupCategory categories = 2;
  total_size += 1UL * this->_internal_categories_size();
  for (const auto& msg : this->_internal_categories()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // repeated .BrokenBackupSource brokenSources = 100;
  total_size += 2UL * this->_internal_brokensources_size();
  for (const auto& msg : this->_internal_brokensources()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // repeated .BackupSource sources = 101;
  total_size += 2UL * this->_internal_sources_size();
  for (const auto& msg : this->_internal_sources()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // repeated .BackupPreference preferences = 104;
  total_size += 2UL * this->_internal_preferences_size();
  for (const auto& msg : this->_internal_preferences()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // repeated .BackupSourcePreferences sourcePreferences = 105;
  total_size += 2UL * this->_internal_sourcepreferences_size();
  for (const auto& msg : this->_internal_sourcepreferences()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Backup::_class_data_ = {
    Backup::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Backup::GetClassData() const {
  return &_class_data_;
}

void Backup::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Backup*>(&to_msg);
  auto& from = static_cast<const Backup&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Backup)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_mangabackup()->MergeFrom(
      from._internal_mangabackup());
  _this->_internal_mutable_categories()->MergeFrom(
      from._internal_categories());
  _this->_internal_mutable_brokensources()->MergeFrom(
      from._internal_brokensources());
  _this->_internal_mutable_sources()->MergeFrom(
      from._internal_sources());
  _this->_internal_mutable_preferences()->MergeFrom(
      from._internal_preferences());
  _this->_internal_mutable_sourcepreferences()->MergeFrom(
      from._internal_sourcepreferences());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Backup::CopyFrom(const Backup& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Backup)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Backup::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Backup::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Backup::InternalSwap(Backup* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.mangabackup_.InternalSwap(&other->_impl_.mangabackup_);
  _impl_.categories_.InternalSwap(&other->_impl_.categories_);
  _impl_.brokensources_.InternalSwap(&other->_impl_.brokensources_);
  _impl_.sources_.InternalSwap(&other->_impl_.sources_);
  _impl_.preferences_.InternalSwap(&other->_impl_.preferences_);
  _impl_.sourcepreferences_.InternalSwap(&other->_impl_.sourcepreferences_);
}

::google::protobuf::Metadata Backup::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tachiyomi_2eproto_getter, &descriptor_table_tachiyomi_2eproto_once,
      file_level_metadata_tachiyomi_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
