name: Compile ChiyoTatsu

on:
    push:
        branches:
            - main

jobs:
    create_release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout ChiyoTatsu
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install build essentials
              run: |
                  sudo apt install -y git
                  wget https://go.dev/dl/go1.22.2.linux-amd64.tar.gz
                  sudo tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz

            - name: Generate Version Number
              run: |
                  CURRENT_VER="$(./increment_version.sh)"
                  echo "CURRENT_VER=$CURRENT_VER" >> $GITHUB_ENV

            - name: Compile ChiyoTatsu [Release]
              run: |
                  export PATH=$PATH:/usr/local/go/bin
                  go build -ldflags="-s -w" -o chiyotatsu.elf ./chiyotatsu.go
                  GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o chiyotatsu.exe ./chiyotatsu.go
                  mv -v chiyotatsu.elf "chiyotatsu-${{ env.CURRENT_VER }}-${{ github.sha }}.elf"
                  mv -v chiyotatsu.exe "chiyotatsu-${{ env.CURRENT_VER }}-${{ github.sha }}.exe"
                  pwd

              # Why u not getting the binaries man?
              # Please don't tell me it's because of the quotation marks...
              # I was using the wrong action too!?
            - name: Create Release and Upload Assets
              uses: softprops/action-gh-release@v2
              with:
                  name: 'Release ${{ env.CURRENT_VER }}'
                  body: ${{ github.event.head_commit.message }}
                  tag_name: ${{ env.CURRENT_VER }}
                  files: |
                      chiyotatsu-${{ env.CURRENT_VER }}-${{ github.sha }}.elf
                      chiyotatsu-${{ env.CURRENT_VER }}-${{ github.sha }}.exe
                  draft: false
                  prerelease: false
