name: Compile ChiyoTatsu

on:
    push:
        branches:
            - main

jobs:
    create_release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout ChiyoTatsu
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Install build essentials
              run: sudo apt install -y git gh build-essential mingw-w64 protobuf-compiler libprotobuf-dev libprotoc-dev libprotobuf-c1 libprotobuf-c-dev

            - name: Generate Version Number
              run: |
                  CURRENT_VER="$(./increment_version.sh)"
                  echo "CURRENT_VER=$CURRENT_VER" >> $GITHUB_ENV

            - name: Compile ChiyoTatsu [Release]
              run: |
                  make elf
                  mv -v chiyotatsu.elf "chiyotatsu-$CURRENT_VER-$GITHUB_SHA.elf"
              env:
                  CURRENT_VER: ${{ env.CURRENT_VER }}

            - name: Create Release
              run: |
                  gh release create "$CURRENT_VER" --draft=false --title "Release? $CURRENT_VER" --body "${{ github.event.head_commit.message }}"
                  gh release upload "chiyotatsu-$CURRENT_VER-$GITHUB_SHA.elf"
              env:
                  CURRENT_VER: ${{ env.CURRENT_VER }}
