name: Compile ChiyoTatsu

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    create_release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout ChiyoTatsu
              uses: actions/checkout@v2
              with:
                  submodules: recursive

            - name: Install build essentials
              run: sudo apt install -y build-essential mingw-w64 protobuf-compiler libprotobuf-dev libprotoc-dev libprotobuf-c1 libprotobuf-c-dev

            - name: Compile ChiyoTatsu [Release]
              run: |
                  make elf
                  mv -v chiyotatsu.elf chiyotatsu-$GITHUB_SHA.elf
                  #export CC=x86_64-w64-mingw32-gcc
                  #export CXX=x86_64-w64-mingw32-g++
                  #make exe
                  #mv chiyotatsu.exe chiyotatsu-$GITHUB_SHA.exe

            - name: Get commit message
              id: get_commit_message
              run: |
                  COMMIT_MESSAGE="$(git log --pretty=format:'-   %s' | head -n1)"
                  echo "name=COMMIT_MESSAGE::COMMIT_MESSAGE" >> $GITHUB_STATE

            - name: Get latest tag or default to v0.0.0
              id: get_latest_tag
              run: |
                  TAG=$(git describe --abbrev=0 --tags 2>/dev/null || echo "v0.0.0")
                  echo "name=TAG::TAG" >> $GITHUB_STATE

            - name: Increment Current Tag
              id: increment_current_tag
              run: |
                  TAG=${{ steps.get_latest_tag.outputs.TAG }}
                  NEXT_TAG=$(echo "$TAG" | awk -F"." '{ print $1"."$2"."$3 + 1 }')
                  echo "name=NEXT_TAG::NEXT_TAG" >> $GITHUB_STATE

            - name: Upload ChiyoTatsu
              uses: actions/upload-artifact@v2
              with:
                  name: release-artifact
                  path: |
                      chiyotatsu-$GITHUB_SHA.elf

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.increment_current_tag.outputs.NEXT_TAG }}
                  release_name: Alpha ${{ steps.increment_current_tag.outputs.NEXT_TAG }}
                  draft: false
                  prerelease: true
                  body: |
                      Notes:

                      ** Commit Message **
                      ${{ steps.get_commit_message.outputs.COMMIT_MESSAGE }}
