name: Compile ChiyoTatsu
on:
    push:
        branches:
            - main

jobs:
    ci-configure:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install compilers
              run: |
                  sudo apt install -y zlib1g{,-dev} libz-mingw-w64{,-dev} \
                  libprotobuf{23,-dev}

            - name: Generate Version Number
              run: |
                  CURRENT_VER="$(./increment_version.sh)"
                  echo "CURRENT_VER=$CURRENT_VER" >> $GITHUB_ENV

            - name: Compile
              run: |
                  make -j4 -f linux_ver.mk
                  mv chiyotatsu.elf chiyotatsu-i686-${{ env.CURRENT_VER }}.elf

            - name: Create Release and Upload Assets
              uses: softprops/action-gh-release@v2
              with:
                  name: 'Release ${{ env.CURRENT_VER }}'
                  body: ${{ github.event.head_commit.message }}
                  tag_name: ${{ env.CURRENT_VER }}
                  files: |
                      chiyotatsu-i686-${{ env.CURRENT_VER }}.elf
                  draft: false
                  prerelease: false
