name: Compile ChiyoTatsu

on:
    push:
        branches:
            - main

jobs:
    create_release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout ChiyoTatsu
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install build essentials
              run: |
                  sudo apt install -y git
                  wget https://go.dev/dl/go1.22.2.linux-amd64.tar.gz
                  sudo tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz

            - name: Generate Version Number
              run: |
                  CURRENT_VER="$(./increment_version.sh)"
                  echo "CURRENT_VER=$CURRENT_VER" >> $GITHUB_ENV

              # Cross compiling to android seems like a pain?
            - name: Compile ChiyoTatsu [Release]
              run: |
                  export PATH=$PATH:/usr/local/go/bin
                  #export CGO_ENABLED=1
                  #GOOS=android GOARCH=amd64 go build -ldflags="-s -w" -o "and-amd64-chiyotatsu-${{ env.CURRENT_VER }}.elf" ./chiyotatsu.go
                  #GOOS=android GOARCH=386   go build -ldflags="-s -w" -o "and-i386-chiyotatsu-${{ env.CURRENT_VER }}.elf"  ./chiyotatsu.go
                  GOOS=darwin  GOARCH=amd64 go build -ldflags="-s -w" -o "mac-amd64-chiyotatsu-${{ env.CURRENT_VER }}.app" ./chiyotatsu.go
                  #GOOS=darwin  GOARCH=386   go build -ldflags="-s -w" -o "mac-i386-chiyotatsu-${{ env.CURRENT_VER }}.app"  ./chiyotatsu.go
                  GOOS=linux   GOARCH=amd64 go build -ldflags="-s -w" -o "lin-amd64-chiyotatsu-${{ env.CURRENT_VER }}.elf" ./chiyotatsu.go
                  GOOS=linux   GOARCH=386   go build -ldflags="-s -w" -o "lin-i386-chiyotatsu-${{ env.CURRENT_VER }}.elf"  ./chiyotatsu.go
                  GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o "win-amd64-chiyotatsu-${{ env.CURRENT_VER }}.exe" ./chiyotatsu.go
                  GOOS=windows GOARCH=386   go build -ldflags="-s -w" -o "win-i386-chiyotatsu-${{ env.CURRENT_VER }}.exe"  ./chiyotatsu.go

              # Why u not getting the binaries man?
              # Please don't tell me it's because of the quotation marks...
              # I was using the wrong action too!?
            - name: Create Release and Upload Assets
              uses: softprops/action-gh-release@v2
              with:
                  name: 'Release ${{ env.CURRENT_VER }}'
                  body: ${{ github.event.head_commit.message }}
                  tag_name: ${{ env.CURRENT_VER }}
                  files: |
                      and-amd64-chiyotatsu-${{ env.CURRENT_VER }}.elf
                      and-i386-chiyotatsu-${{ env.CURRENT_VER }}.elf
                      mac-amd64-chiyotatsu-${{ env.CURRENT_VER }}.app
                      mac-i386-chiyotatsu-${{ env.CURRENT_VER }}.app
                      lin-amd64-chiyotatsu-${{ env.CURRENT_VER }}.elf
                      lin-i386-chiyotatsu-${{ env.CURRENT_VER }}.elf
                      win-amd64-chiyotatsu-${{ env.CURRENT_VER }}.exe
                      win-i386-chiyotatsu-${{ env.CURRENT_VER }}.exe
                  draft: false
                  prerelease: false
